### ISSUE TITLE
Remarks on the Notes plugin

### ISSUE THREAD

**Issue by PhiLhoSoft** [hluk/CopyQ#1004]
I experimented a bit with the Notes feature, so I added some notes on permanent items in a personal tab.
I was surprised to see the notes displayed twice: once before the text of the item, and once below, in full.
Why this redundancy?

If I choose to display only the icon, it removes the full display of notes, so the redundancy disappears.
But then, there is another surprising behavior: the popup / tooltip with the full note content is displayed only when we select the item. Why this limitation?

Also I searched a page documenting the Notes feature, hoping to find answers, but I failed to find one. Perhaps because it is a simple feature?

**Comment by hluk** [comment]
Can you provide screenshot?

**Comment by PhiLhoSoft** [comment]
I forgot an important information: the "Show simple items" option was activated.

Regular mode is OK:
![copyq-notes-0](https://user-images.githubusercontent.com/1087902/45926974-ee75da00-bf2b-11e8-92bf-b26e97b70ad6.png)

With the simple items option:
![copyq-notes-1](https://user-images.githubusercontent.com/1087902/45926975-ee75da00-bf2b-11e8-9b4c-539cd4851e00.png)

With only the Notes icons.
![copyq-notes-2](https://user-images.githubusercontent.com/1087902/45926976-ee75da00-bf2b-11e8-98dc-c8a0eb2429ba.png)

**Comment by zzl93** [comment]
我认为不用移除吧，如下图，这样我不能直观的知道每条信息所代表的意思，需要鼠标放上去才能知道
![image](https://user-images.githubusercontent.com/15900227/46593718-c4621180-cb00-11e8-9803-8235b34e0807.png)

**Comment by hluk** [comment]
Hmm, showing just the icon doesn't seem to be useful at all and getting the notes in tooltip when hovering mouse over item looks annoying.

I can replace the "Icon Only" and "Show Tool Tip" options with "Next to Item" -- to show the tooltip next to the item (left side in left-to-right writing systems, right otherwise). Maybe the notes can be then shorten (with `...`) depending on size of the item.
