### ISSUE TITLE
both taskbar and tray icon doesn't look good

### ISSUE THREAD

**Issue by bsucker98** [hluk/CopyQ#1066]
both icons edges are too sharp(I don't know how to explain that, see the photo) and also tray icon is bit bigger, sorry if not an issue of the app but the **OS**, I'm using **Solus OS**
![screenshot from 2019-01-08 11 55 11](https://user-images.githubusercontent.com/38057676/50813449-67af0680-133c-11e9-9f91-ad9ab449f7e6.png)

**Comment by hluk** [comment]
> sorry if not an issue of the app but the **OS**, I'm using **Solus OS**

Yeah, looks like issue in your current icon theme. Probably this one: https://github.com/PapirusDevelopmentTeam/papirus-icon-theme

**Comment by bsucker98** [comment]
ah!

**Comment by hluk** [comment]
> ah!

Actually, it still could be an issue in CopyQ or Qt framework. So let me double check.

**Comment by hluk** [comment]
Nothing about how the app provides the icon changed recently. It's possible, that the ugly tray icon is caused by Qt - I myself am waiting for Qt 5.12 to be available on my distro so that some tray glitches in Qt apps are fixed.

Another wild guess is that providing more icons sizes ([this list in the code](https://github.com/hluk/CopyQ/blob/ee3b610b653872c813b51e62922aaf205f8a4b0c/src/gui/iconfactory.cpp#L531)) would be enough to fix this.
