### ISSUE TITLE
Inkscape / CopyQ issue

### ISSUE THREAD

**Issue by kzoli429** [hluk/CopyQ#1073]
I have been using Arch Linux with Linux 4.20.0-arch1-1-ARCH #1 SMP PREEMPT Mon Dec 24 03:00:40 UTC 2018 x86_64 GNU/Linux

My CopyQ version is CopyQ 3.7.2

While CopyQ is running, the occurrence is the following:

    Inkscape (version 0.92.4 5da689c313, 2019-01-14) started
    Simple shape, i.e. rectangle, drawn
    Shape copied; i.e. by Copy+C, Menu/Edit/Copy, right click + Copy
    Another window appears with a message:
    " Inkscape has received additional data from the script executed.  The script did not return an error, but this may indicate the results will not be as expected."
    See also attached screenshot.

![image](https://user-images.githubusercontent.com/17426685/51616725-fc178c80-1f2a-11e9-83a4-06340538c6f7.png)

When I exit from CopyQ then Copy/Paste can be done without event. Having CopyQ running, the message is displayed again, repeatably.

Path for extension referred: usr/share/inkscape/extensions/inkex.py

**Comment by hluk** [comment]
This looks like a bug in Inkscape (I suppose CopyQ is requesting an image format from clipboard and Inkscape cannot provide it because it's missing a library).

Did you try installing the wrapper mentioned in the message box?

I think this can be also fixed by disabling Image plugin in CopyQ if you don't need to store images from clipboard.
