### ISSUE TITLE
sync clipboard and selection went away in 3.7.3?

### ISSUE THREAD

**Issue by richey-v** [hluk/CopyQ#1092]
I've been using CopyQ for a while and prefer the behavior where clipboard and primary selection are synchronized.

Has that behavior been removed or do I just have to configure it in a different way?

I'm on Xubuntu (XFCE4) Xenial (16.04.5) using CopyQ package from `http://ppa.launchpad.net/hluk/copyq/ubuntu xenial`.

**Comment by hluk** [comment]
It's still supported. In configuration dialog you should see:

> ![image](https://user-images.githubusercontent.com/38054/52909997-5b9a5b00-3291-11e9-84f2-bb3ef6004efc.png)

Quick test:

```bash
echo "Selection synchronized" | xclip && sleep 1 && copyq clipboard
```

This should set X11 selection using `xclip` and after short delay print clipboard content, which should be "Selection synchronized" if the sync was successful.

There are is an issue in latest version - if selection changes faster, clipboard may contain older selection instead of the new one. I already have a fix planned for next release.

**Comment by richey-v** [comment]
Yep, working fine!  Maybe I was hitting the selection change issue when I was trying options.
