### ISSUE TITLE
CopyQ Causes Left Control Key to be Stuck Down (in Windows)

### ISSUE THREAD

**Issue by dbareis** [hluk/CopyQ#1139]
I recently upgraded a 2 year old version of **COPYQ to v3.8.0.** Soon after I started having issues I hadn't seen before.  Sometimes restarting COPYQ cleared them sometimes not, I'd then need to reboot the computer.

I have worked out the issue is that the **left control key is being held down** (as far as Windows is concerned), this causes weird typing and mouse scroll wheel behaviour.  

Once I recognise weird things are happening, the recovery action is to press and release the left control (CTRL) key.

_I do not know how to reproduce this yet._ I'm on **Windows 10 64 bit**.

**Comment by hluk** [comment]
It could be caused by pasting an item from CopyQ (either from main window or tray menu). The app simulates Shift+Insert (or Ctrl+V) to paste the clipboard.

Is there any error in log (F12 shortcut)?

**Comment by hluk** [comment]
Actually, I'm pretty sure it's caused by binding a shortcut with Ctrl key to paste action. The code to paste first needs to send "key up" event, but after the paste is finished it sends "key down" event again so you can use the shortcut again without releasing Ctrl key.

I believe that it breaks if you release the Ctrl modifier before, CopyQ "presses" it for you again.

Relevant code:

https://github.com/hluk/CopyQ/blob/193e3ab09c8e2dd454c876849b848fdaefb740df/src/platform/win/winplatformwindow.cpp#L177

**Comment by hluk** [comment]
This works differently on Linux/X11, where CopyQ waits for all keyboard modifiers (Shift, Ctrl, etc.) to be released by user before sending the paste shortcut.

Maybe I can make the behavior same here, but you would need to release Ctrl/Shift to be able to use it again.

**Comment by dbareis** [comment]
I'll try to keep an eye out for the issue to occur again and get the log.  There were some entries there but I was not sure whether they came from the problem or from me restarting the app.

The 2-year-old version of the app didn't have this problem.

**Comment by dbareis** [comment]
This is still happening (maybe less frequently, forgot to get the log)

**Comment by hluk** [comment]
Do you use v3.9.2? It avoids pressing the key modifiers again.
