### ISSUE TITLE
Increase History Size to 99 999

### ISSUE THREAD

**Issue by luapfr** [hluk/CopyQ#1144]
Currently the Historico has a limit of 9 999 would be very interesting an addition, as I am a programmer I use a lot of Transfer, and the Limit of 9 999 is easily reached.

With 99 999 it would be perfect.

Thankful.

**Comment by hluk** [comment]
Depending on what you store in the app, even 10k items can be too much data. Opening such tab slows down that application too much (CopyQ uses simple data format to store tabs).

I won't increase the limit unless the data format changes.

It's better to use tabs to mange huge number of items. There are couple of commands that simplify this.

If you really need this and since you're a programmer, you can try changing the limit in code and recompile the app. But if you use other formats than plain text you might see performance regressions.

**Comment by luapfr** [comment]
First of all, for the excellent work done with CopyQ, this program is by far one of the best that exists in this activity.

  I am programmer in Delphi "Pascal" I do not know how to program in C ++
but everything I copy is plain text, so I believe it would not be so slow.

   Another way of solving is when you reach Historical Limit create a Backup or Automatic Guide with Archiving Month and Year.

**Comment by skamensky** [comment]
@luapfr , I bumped into this issue as well. Check out this backup script I wrote which backs up plain text clips to a local searchable sqlite database

https://github.com/skamensky/backup-copyq

**Comment by ab503044120** [comment]
maybe you can Add a function that can switch the history database

**Comment by hluk** [comment]
Fixed in #2541. This will be available in the next release with performance improvements related to tab/item data.
