### ISSUE TITLE
Whenever the main window is tried to close, it gets minimized instead.

### ISSUE THREAD

**Issue by SDey96** [hluk/CopyQ#1162]
**Bug Description**
Whenever I try to close the main window, it doesn't get closed, but instead gets minimized to the dash. I started using it recently on Fedora 30 on a Wayland session, and I am not really sure whether or not that is a feature.

**To Reproduce**
1. Close the main window of CopyQ.

**Expected behavior**
The main window should be closed immediately without affecting the `copyq` server running status.

**Version, OS and Environment**
 - Application Version: 3.8.0
 - OS: Fedora 30 (Workstation Edition; Wayland session)
 - Desktop environment: GNOME (stock, without any theming)

**Comment by hluk** [comment]
This is not a but. If there is no tray icon by default the main window minimizes when closed. Otherwise there would be no way to show the window without using command line or a global shortcut (this can be confusing for new users).

You can change the behavior by enabling "Hide main window" in "Layout" configuration tab.

**Comment by SDey96** [comment]
> You can change the behavior by enabling "Hide main window" in "Layout" configuration tab.

Thanks a lot, this is what I needed!
