### ISSUE TITLE
An option to disable the Taskbar Button

### ISSUE THREAD

**Issue by berlihingen** [hluk/CopyQ#1176]
I never hide the main window (128px wide fixed to desktop side like a widget) so clipboard history is always visible/accessible. In such config, not only tray icon but also taskbar button is just a waste of space. Thanks.

**Comment by hluk** [comment]
Looks like this is not difficult to do but I'm not sure if it's a good idea to add the option to configuration because for normal user who doesn't use global shortcuts or command line to show main window the application could be inaccessible (hidden window, tray icon and task bar entry).

I have patch where you can set `hide_main_window_in_task_bar=true` manually in the configuration file (you need to exit the app first).

There are couple of other hidden options. Maybe I can at least make them modifiable using `copyq config <OPTION> <VALUE>` command.

**Comment by berlihingen** [comment]
Yes, I've already lost my window and managed to get it back via copyq.ini+copyq-bak.ini (only one wasn't enough). Where can I get this patch?

**Comment by hluk** [comment]
> Where can I get this patch?

The patch is in git branch [hide-in-task-bar](https://github.com/hluk/CopyQ/commits/hide-in-task-bar).
