### ISSUE TITLE
Feature request: native Linux desktop notifications

### ISSUE THREAD

**Issue by infokiller** [hluk/CopyQ#1247]
**Is your feature request related to a problem? Please describe.**
I want to be able to manage all my notifications centrally on my Linux computers.
When programs send [XDG notifications](https://developer.gnome.org/notification-spec/), they can be managed using a notification daemon such as [dunst](https://github.com/dunst-project/dunst), which enables you to:
- Customize the appearance of notifications
- Define rules such as "if the notification contains this text, don't show it", 
- Define keyboard shortcuts to dismiss notifications, show the previous one again, etc.
- Keeps an history of sent notifications

**Describe the solution you'd like**
An opt-in option for sending native notifications on Linux.

**Describe alternatives you've considered**
Implementing all the above features in the notification mechanism that CopyQ uses.

**Comment by hluk** [comment]
So I decided to look into this and tried using notifications from KDE Frameworks which seems pretty good and supports all required platforms (otherwise, I would not be willing to spend time implementing this myself).

Everything seems to work, except Windows build (failing to build the dependencies). :(

If you want to build it and try it out, see [knotifications branch](https://github.com/hluk/CopyQ/tree/knotifications).

You need to install additional dependencies for building CopyQ:

- Ubuntu: `libkf5notifications-dev`, `extra-cmake-modules`
- Fedora: `kf5-knotifications-devel`, `extra-cmake-modules`

**Comment by hluk** [comment]
I managed to build the Windows binary but there are some problems:

1. The dependency handling is not easy.
2. It adds more than 10 minutes to binary build.
3. It adds 10-15MiB to the setup/zip.
4. I'm still failing to build some dependencies with msvc (only MinGW build works).
5. Looks like Windows 7 is unsupported.

**Comment by infokiller** [comment]
Many thanks @hluk for tackling this so quickly, you're awesome!
I'll try the branch now.

Re the issues you mention, are they caused because the KDE libraries are bloated?

Supporting Linux should be easy: you can just use call `notify-send` executable (you can also use a library, but that may introduce more dependency issues on the other platforms).
For supporting Mac and Windows, I'm not sure.

**Comment by infokiller** [comment]
Just tested the knotifications branch and it works well on ArchLinux!

**Comment by amerlyq** [comment]
@infokiller can you consider making alternative AUR pkg "copyq-notify-git" or something, due to building this thing into main package was decided as not feasible?

**Comment by infokiller** [comment]
@amerlyq I'm not really interested in that because I try to avoid AUR packages

**Comment by hluk** [comment]
Closing; New issues to use native notifications: #1503
