### ISSUE TITLE
CopyQ crashes without warning

### ISSUE THREAD

**Issue by stephenaustin** [hluk/CopyQ#1311]
**Describe the bug**
CopyQ opens shows only in the Task Bar. Clicking on icon momentarily opens the app. Any attempt to do anything closes it down.  attempting to run it on two Windows and one Linux device. Sync it via Dropbox but problem persists even when Dropbox files are removed. 

**To Reproduce**
1. Go to 'Windows button'
2. Click on 'Copyq'
3. Copq appears in task bar. 
4. Clicking on it makes the app run momentarily
5. Then it closes
**Expected behavior**
It should run normally. 

Log files attached

**Version, OS and Environ
[copq_log.txt](https://github.com/hluk/CopyQ/files/4170050/copq_log.txt)
[copq_log_3.10.txt](https://github.com/hluk/CopyQ/files/4170051/copq_log_3.10.txt)

 - Application Version [e.g. 3.10.0
 - WIndow 10.0.18363 build 18363
 - Desktop environment, window manager (if applicable)

**Additional context**
Have tried uninstalling and removing all the old directories and reinstalling.

**Comment by limpep** [comment]
Can confirm having the same issue on. 

Version: 1909
Build: 18363.628

**Comment by hluk** [comment]
> Have tried uninstalling and removing all the old directories and reinstalling.

You mean it crashes even if the sync is not enabled? Or does it crash only on Windows with sync enabled?

**Comment by richlux** [comment]
I have frequent crashes on Windows with sync enabled. It's definitely related to sync because I have no issues when sync is disabled.  Sometimes CopyQ will just crash when I click on an item in the list.  Sometimes it crashes when I copy an item.  There doesn't seem to be any pattern that I can determine.  I've just been living with it because sync is a must for me.

Rich

**Comment by kaleb4eg** [comment]
I just have installed it in MacOs Mojave using `brew cask install copyq` and app is not launching at all - when I click on icon it just blinks and do nothing.

**Comment by Zackhardtoname** [comment]
I have frequent crashes on Ubuntu 18.04 as well. I actually just lost important work.

**Comment by hluk** [comment]
> I have frequent crashes on Ubuntu 18.04 as well with version 3.10. I actually just lost some important work.

Can you provide backtrace/stacktrace/core-dump or something? Not sure what Ubuntu uses for this.

**Comment by richlux** [comment]
This is still happening to me multiple times a day on Windows 10.  Sometimes after I do a copy, it will crash (I'll notice that the tray icon is the closed scissors and when I hover over it, it disappears). There is, however, one thing that always causes it to crash: Often I'll see an entry in the clipboard list that simply says <EMPTY> and clicking on that entry will always cause CopyQ to crash. Other than that, it seems totally random although I'm sure it's not.

Thanks, 
Rich

**Comment by richlux** [comment]
I was just wondering if there was anything I can do to help diagnose this issuer on Windows.  It's constantly crashing multiple times a day even when just browsing the list of clips.  I think this is related to the synchronize feature using a shared drive because I had no problems at all until I started using synchronization. That said, I'm often seeing entries in the clipboard list that say <EMPTY> and whenever I see this, CopyQ always crashes when I'm clicking around in the clipboard list.  Again, I'm happy to install a debug version or something if it helps.  Just let me know.

Thanks,
Rich

**Comment by hluk** [comment]
Unfortunately, I never managed to get the Windows debug version work properly so it gives some helpful information about crashes.

The simplest way is to set up development environment:

1. Install Qt Creator and CMake -- should be possible using Chocolatey: `choco install qtcreator cmake`
2. Download and unpack source code: https://github.com/hluk/CopyQ/archive/v3.10.0.zip
3. Start Qt Creator.
4. Open `CMakeLists.txt` from the source code.
4. Press F5 and hope it will build and run.

It's probably not that easy, I haven't tested this. I believe Qt Creator installation contains Qt libraries, but if not, you may need to install them manually and set up Qt Creator.

**Comment by richlux** [comment]
I haven't setup a development environment yet, but I believe I have found at least one of the causes of the crashes. The <EMPTY> entries seem to be caused when I have synchronization enabled and have a clipboard entry that is "pinned".  I can duplicate the issue with the following steps:
1) Pin an entry on computer 1
2) Computer 2 shows the entry correctly
3) Copy some text on one of the computers (control-c)
4) The other computer now shows <EMPTY> where it used to show the pinned item.  Now anything done in CopyQ on this computer will crash it.  Unpinning the item from the original computer fixes the issue.

Rich

**Comment by hluk** [comment]
Thanks, @richlux. I fixed the behavior with pinned items.

Development version with the fix is here: https://ci.appveyor.com/project/hluk/copyq/builds/32091029/job/gi781wm3skbb0r0b/artifacts

**Comment by richlux** [comment]
In my limited testing so far, it looks like this fixes the issue.  Thank you!!

Does this build also include the fix for https://github.com/hluk/CopyQ/issues/1309?  If so, it looks like it the issue still exists.  The original issue doesn’t say it, but this happens with URLs also.  If I move a previously copied URL into the clipboard, when I paste it, I don’t get the URL text, I get file attachments instead.  I’ve tested with both Microsoft Word and Outlook emails.  See the examples below.  (FYI, Images moved to the clipboard paste correctly in Microsoft Word, but still create attachments in Outlook emails)

Given these URLs in the clipboard list:
 
![image](https://user-images.githubusercontent.com/25157703/78999514-d0c19300-7b18-11ea-8d72-40715c49f40c.png)



Moving **URL 1** above into the clipboard and then pasting into Microsoft Word or Outlook, I get this embedded file below instead of the URL text:
 
![image](https://user-images.githubusercontent.com/25157703/78999524-d5864700-7b18-11ea-93e3-36ff285f1e11.png)


Moving **URL 5** above into the clipboard and then pasting into Microsoft Word or Outlook, I get the 3 embedded files below instead of the URL text. Probably because URL 5 has and Icon and Notes:
 
![image](https://user-images.githubusercontent.com/25157703/78999532-d8813780-7b18-11ea-9318-fb25b1f080f3.png)


Thanks,
Rich

**Comment by hluk** [comment]
> In my limited testing so far, it looks like this fixes the issue. Thank you!!

Glad it works. Thanks for testing.

> Does this build also include the fix for #1309? If so, it looks like it the issue still exists.

Can you move this to the other issue if it's unrelated to this one?

**Comment by richlux** [comment]
Sure, but that issue is closed. Is there a way to re-open it?

Rich

**Comment by hluk** [comment]
> Sure, but that issue is closed. Is there a way to re-open it?

Reopened (not sure if users cannot really do this).
