### ISSUE TITLE
"UTF-8"  (ignore diacritics) search

### ISSUE THREAD

**Issue by pato7** [hluk/CopyQ#1318]
Would it be possible to implement "UTF-8" (ignore diacritics) search? E. g. if you search for "vacsina" it would also find "väčšina" and vice versa.

**Comment by hluk** [comment]
This might be too complicated to implement [1] and, to be honest, I never needed it in CopyQ (but I do mostly code search of finding some English text).

[1] https://stackoverflow.com/questions/14009522/how-to-remove-accents-diacritic-marks-from-a-string-in-qt

**Comment by hluk** [comment]
Got an idea how to implement this from [A Crash Course in Unicode for C++ Developers - Steve Downey - [CppNow 2021]](https://youtu.be/iQWtiYNK3kQ).

If the original text does not match the search, the implementation falls back to search in the same text but with accents/diacritics removed. Removing ascents is done by decomposing the unicode text and removing non-spacing marks (Mn).

If the original text matches there is no fallback since the text conversion can be computationally expensive.

Interestingly, highlighting matched text works well even in fairly complex rich text samples. Though I expect this can break in some more complicated HTML documents - in such case it would show the highlight in a slightly different place.
