### ISSUE TITLE
Is there a way  to save/export images

### ISSUE THREAD

**Issue by therajat08** [hluk/CopyQ#1387]
Request to export to png or jpeg image

**Comment by hluk** [comment]
This command should help: [Save Item/Clipboard To a File](https://github.com/hluk/copyq-commands/tree/master/Application#save-itemclipboard-to-a-file)

See the README file in the repo for details on how to install the command: https://github.com/hluk/copyq-commands/blob/master/README.md

**Comment by therajat08** [comment]
i did what you told, but doesn't save the image. All it does id display a pop message as :
![image](https://user-images.githubusercontent.com/22724490/86527641-b51f1c00-bebe-11ea-8fbf-86b4a2ab12c1.png)

In the home there is n directory by my name "rajat"

**Comment by bonnebulle** [comment]
Hey
It's been a long time since I came here for help
Cant find any Commande to export a lot of image items selected (once)
The Commande here only works for individual item
I would like to export multiple items at once
Can you help ?
Thanks for the magick

Partialy related to https://github.com/hluk/CopyQ/issues/1616 (individual export/Save as...)

I finaly use the Synchronisation function to automaticly recover the copyq images

<img width="940" height="454" alt="Image" src="https://github.com/user-attachments/assets/081a68f8-de8b-4363-9b7b-c8c470ded3e8" />
