### ISSUE TITLE
Pin indicator not clearly visible when using dark theme

### ISSUE THREAD

**Issue by Gitoffthelawn** [hluk/CopyQ#1398]
**Describe the bug**
When using a dark theme (dark background, light text), the pin indicator is not clearly visible.

**To Reproduce**
1. Configure a dark theme
2. Pin an item
3. Notice the pin indicator is not easily visible

**Expected behavior**
Pin indicator clearly visible in all themes.

**Version, OS and Environment**
CopyQ Clipboard Manager v3.11.1
Qt: 5.13.2
Compiler: GCC
Arch: i386-little_endian-ilp32
OS: Windows

**Additional context**
Perhaps adding this to the built-in Appearance UI would be good.

**Comment by hluk** [comment]
Currently, the color is derived from background:

```
if background is light
    color = backgroundHSL
    color.lightness -= 200
else
    color = backgroundHSL
    color.lightness += 50
end
```

For the dark background it really seems that the bar is not much brighter. Let me increase the brightness.

As a workaround, you can change the style somewhat (not the gray right-hand side bar), by adding a new style to `shared/item.css`:

```css
ItemPinned #item_child {
    border-left: 8px solid rgba(255, 255, 255, 150);
    padding-left: 8px;
}
```

Adding a new color option to Appearance config tab would be difficult because Pin Item is basically plugin and plugins don't support this.
