### ISSUE TITLE
Having trouble 'on-boarding' coming from other clipboard managers

### ISSUE THREAD

**Issue by Newman5** [hluk/CopyQ#1405]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to copy and paste from the Clipboard manager.  

**Describe the solution you'd like**
I expect to have a keyboard shortcut for pasting from the manager. For example, I used Ditto.  I would press CRTL ` to bring up the clipboard window and then CRTL + <the number of the item to be pasted>.  Another manager I used, I would use Windows Key + V to bring up the window and then ... I think I pressed the number of the item I wanted pasted 

**Describe alternatives you've considered**
I am able to set a shortcut to bring up the main window and I can see the items, and I can use the mouse to select an item to paste.  Is there a keyboard shortcut to paste an item?

**Additional context**
I see this repo has alot of activity and I want to love this program... but man, getting started has been tough.  It seem like a simple function of getting in and out of the clipboard is difficult.  Any advice for someone getting started?  The docs seemed to be not for my use case.  Anyway, thanks for reading and any help you can give would be appreciated.

**Comment by Newman5** [comment]
ugh.  I'm going to leave that issue up.  I guess I had a tough time figuring out how to use the basic feature of copying a bunch of stuff and then getting it / pasting it back out of the program.  

Here's what I do now - I created a keyboard shortcut to open the main window.  I see the number of clipboard item I want to paste. I press that number key, which searches for it and displays it alone in the window. I then can press the enter key to paste it and the window goes away.  

Maybe it's just me, but that seemed harder than necessary to figure out.  Thanks for reading. Have a great day.

**Comment by hluk** [comment]
Do you have any suggestion? Where did you try to look up the documentation?

Maybe showing a help popup after the app is launched for the first time would help. Something that would allow setting the most commonly used options:
- show/hide shortcut
- automatic clipboard storing on/off
- clipboard notifications on/off
- import old configuration

**Comment by Snowy556** [comment]
There's certainly a learning curve with CopyQ compared to other managers, like Phrase Express.
Don't get me wrong, I absolutely LOVE the program, and it's Free so I can use it at work without violating license agreements (Like Phrase Express' personal use only license) but it did take some learning and coding to have the program do what I wanted.

I use phrase express mostly for templates, as I work in application support, which required me to copy over the snippets command, and modify it. This required some coding, and a lot of trial and error, but I do like the control I have over the program. 
Coming from a paid for solution in Phrase Express, CopyQ is more complicated, and more needs to be coded, as there is not an easy GUI solution for most of my own uses.

I'm no stranger to dirty hacks, but it feels like most of my commands are hacking around the system to accomplish what I want to do.

For example, I coded the following to insert a string of text after my current clipboard contents, which is simple now, but being a stranger to QT code, this took several hours for me to make:

```
copyq:
var otext = str(clipboard())
var text = str(otext) + str('?support=true')
text = text.replace(' ', '')
copy(text)
paste()
copy(otext)
```
I also made this command to automatically paste the first thing in the snippets tab when a keyboard shortcut is pressed, which again, is pretty simple now, but took a lot of time deconstructing the Snippets command, and understanding how snippets were selected and used.

```
copyq:
var otext = str(clipboard())
tab("Snippets")
var text = read(0)
copy(text)
sleep(100)
paste()
copy(otext)
```

Maybe a dedicated page for the snippets command would have been very helpful for me personally, as this is the biggest feature I was looking for in CopyQ myself.

**Comment by pbodnar** [comment]
@all, thanks for sharing your thoughts. As might be seen from my various activities on this project, while I find this app a great one, the documentation is IMHO really not that "newbies-friendly" in the sense that it would describe the most common scenarios or that it would give a quick introduction on how to handle the (custom) commands.

And as I'm not a big fan of video tutorials, because I'm too lazy to create some, but also because you never know if you will actually learn something useful from them, I wrote some introductory blog posts dedicated to CopyQ:

* https://programmedbycoincidence.blogspot.com/2020/02/copyq-for-impatient-introduction.html
* https://programmedbycoincidence.blogspot.com/2020/03/copyq-most-useful-commands.html

I wonder what do you guys think about them and whether they can at least give some inspiration on which topics to focus on.

BTW I think it would also be great to create an easy to read tutorial on how to start writing custom commands, starting from the easiest things like basic clipboard manipulation, getting input from user and gradually getting to some more advanced topics. And maybe also to add some tips on how to write / tune the commands efficiently...
