### ISSUE TITLE
suggestion: set tags font size and colors

### ISSUE THREAD

**Issue by elig0n** [hluk/CopyQ#1421]
In Configuration -> Appearance there is no option to set color or font settings for Tags.

I'm also showing copy times for items in tags [with this command](https://copyq.readthedocs.io/en/latest/command-examples.html#show-copy-time) which make it cumbersome to read as the font is very small.

**Comment by hluk** [comment]
The tag font is by default a smaller version of the font used for items. I can add an option to modify the size in the Tags plugin settings page (but not into Appearance settings since this is option related to a plugin).

Currently, you can change the default font size in the Tags settings by modifying style sheet for all tags:

![image](https://user-images.githubusercontent.com/38054/85433131-45d32f00-b584-11ea-98f1-4c7d766eaa59.png)

(Add `\1` as tag name, `(.*)` as Match and `font-size: 10pt` as Style Sheet.)

See also: https://copyq.readthedocs.io/en/latest/tags.html

Or you can change the font size by adding following to `themes/items.css`:

```css
ItemTags QWidget {
    font-size: 10pt;
}
```

**Comment by elig0n** [comment]
What is the location of items.css?

**Comment by hluk** [comment]
> What is the location of items.css?

You can copy the correct path by opening Action dialog (F5) and executing command:

```js
copyq:
var d = Dir(info('config'))
d.cdUp()
d.cd('themes')
copy(d.absolutePath())
```

BTW, you don't have to quit the app to reload the style sheets -- to do that open Configuration dialog (Ctrl+P) and press OK.

**Comment by elig0n** [comment]
@hluk Using your command I've gotten the path : `C:/Users/%MYUSER%/AppData/Roaming/copyq/themes`
which I already put an items.css file in it with the following:

    ItemTags QWidget {
	font-size: 20pt;
    }

Yet tags font size doesn't change.  
The other method does work.
I'm running CopyQ v3.10.0

**Comment by hluk** [comment]
You need to update to the latest version to use the stylesheets.

I don't know why the Tags settings method doesn't work for you (should work in older versions of CopyQ).

**Comment by elig0n** [comment]
I said tat Tags settings method does work.
Thanks

**Comment by hluk** [comment]
> I said that Tags settings method does work.

Oh, sorry, misread it. Glad it works.
