### ISSUE TITLE
Question: Duplicate entries

### ISSUE THREAD

**Issue by aksr** [hluk/CopyQ#1431]
Is there a *quick* to delete duplicate entries from the tab (~9000 items)?

**Comment by hluk** [comment]
For text items---ignoring other data in the items, checking only text---you could use this command:

```ini
[Command]
Command="
    copyq:
    var items = {}
    for (var row = 0; row < size(); ++row) {
        var text = str(read(row))
        if (!text)
            continue
    
        if (text in items) {
            remove(row)
            --row
        } else {
            items[text] = true
        }
    }"
Icon=\xf87d
InMenu=true
Name=Remove Text Duplicates
```

But if care about images, tags, notes and other data, you would probably need something more complex.

Reading the items in batches (less `read()` calls) would also improve the performance because the above version can be slow with many items.

**Comment by aksr** [comment]
Works perfectly!  Thank you.

**Comment by mbakstars** [comment]
Is this linked on the commands page? I am thinking not; I just found it and it is a life saver (for how I use the program), and I'm a long time user. =)
