### ISSUE TITLE
How to open link directly from copyQ? 

### ISSUE THREAD

**Issue by pikaboo** [hluk/CopyQ#1519]
**Is your feature request related to a problem? Please describe.**
I am storing a lot of sorted data, some of it is links

**Describe the solution you'd like**
Double click the clipboard item and if it contains only a link, open it in the default browser

**Describe alternatives you've considered**
Doing it manually, but it's too daunting

**Comment by laur89** [comment]
Look up scripting in copyq, that's likley the answer. Guess adding a `run` command that then executes selection via `xdg-open`; or something else, depends on your platform.

**Comment by hluk** [comment]
To open a link from CopyQ: Select the item with link and hold shift so you can click the link.

I think a made it this difficult because I often accidentally opened links from CopyQ.

As @laur89 mentioned, you can override the default double click behavior. There is predefined command **Open in Browser** ([here is how to add such command](https://copyq.readthedocs.io/en/latest/faq.html#how-to-open-copyq-window-or-tray-menu-using-shortcut)) - just assign <kbd>Enter</kbd> key as a shortcut to be able to trigger the action on double-click.
