### ISSUE TITLE
[Feature request] start CopyQ on Windows startup

### ISSUE THREAD

**Issue by Vixb1122** [hluk/CopyQ#1523]
**Is your feature request related to a problem? Please describe.**
The application have to be run manually after system startup.

**Describe the solution you'd like**
provider a preference to start CopyQ on system startup

**Describe alternatives you've considered**
none

**Additional context**
windows 10

**Comment by hluk** [comment]
This is supported by the installer. I haven't found an easy way to do this from the app and I don't have much reason to implement this (honestly, this should be supported by OS/desktop-environment and not by every app).

See also: #1035

**Comment by kendofriendo** [comment]
Sorry for commenting in a close issue, but this is where the google rabbit hole led.

The easiest way is placing a shortcut to the executable in `%APPDATA%/Microsoft/Windows/Start Menu/Programs/Startup`. Users can do this manually by simply copying the exe from the install directory, visiting the above directory, and right clicking and selecting "paste shortcut" from the context menu. The coding side would involve something like the following: a checkbox gui item that checks that directory for the copyq shortcut's existence. If it already exists, the checkbox's state would be checked. If it doesn't not exist, the checkbox would be unchecked. If the user clicks the checkbox when it is in the unchecked state, then create the shortcut in that directory. If the user clicks the checkbox when it is in the checked state, delete the shortcut.

I apologize if the language is vague, but since I don't know C++ I thought I should keep it general. I guess figuring out how to create a Windows shortcut would be the troublesome part.

**Comment by SuperSandro2000** [comment]
The installer can't easily drop another lnk file based on a setting described as in https://github.com/hluk/CopyQ/issues/1035#issuecomment-607610986 ?

Basically the lnk dropped into the startmenu also needs to appear in ``C:\Users\%USERNAME%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup``
