### ISSUE TITLE
Override windows shortcut key WIN + V KEY

### ISSUE THREAD

**Issue by EAZY5D** [hluk/CopyQ#1668]
**Right now it's impossible to use WIN + V key as a shortcut in CopyQ on windows**
It would be great if CopyQ does Just that as users "ME 😅" are quite used to WIN + V Key already but this offers more and switching to ALT V seems too robotic.

**JUST COMPLETE OVERRIDE OF THE WIN + V KEY**
Clipboard Master does this just fine but it's too old style 🤢🤧. 
It would be great if CopyQ allows users to use the WIN + V KEY on windows

**Comment by hluk** [comment]
Mapping the Win keyboard modifier normally works fione. Maybe it is some issue with keyboard layout or remapped keys in system.

**Comment by monoblaine** [comment]
@EAZY5D Windows swallows the <kbd>WIN</kbd> + <kbd>V</kbd> event even if you turn off clipboard history feature. In order to use this shortcut in CopyQ you need to run the following command in a command prompt:

```cmd
reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v "DisabledHotkeys" /t REG_SZ /d "V" /f
```

Then reboot your computer. <kbd>WIN</kbd> + <kbd>V</kbd> should be free now.

Source: https://superuser.com/questions/630112/disable-taskbar-hotkey/725556#725556

**Comment by EAZY5D** [comment]
Thank you that works too.

**Comment by EAZY5D** [comment]
If you don't want to Play around with **Regedit** then Download [PowerToys](https://docs.microsoft.com/en-us/windows/powertoys/) and remap your "Alt+V" to "Win + V"

![image](https://user-images.githubusercontent.com/55167211/145647487-824ffccd-3038-4093-9cdc-50d5528e5fa1.png)
you should have smt like this now

![image](https://user-images.githubusercontent.com/55167211/145647502-cbf51ff9-8e13-45dc-a630-6a015fcce22a.png)

Now set COpyQ ShortCut to "Alt + V" and you are good to Go "Win + V" works like magic
