### ISSUE TITLE
replace underscores with spaces ?

### ISSUE THREAD

**Issue by u53r55** [hluk/CopyQ#1674]
can someone help me?
replace automatic clipboard text with _ to " "

OpenJDK11U-jre_x64_windows_hotspot_11.0.10_9

-> OpenJDK11U-jre x64 windows hotspot 11.0.10 9

**Comment by hluk** [comment]
Clipboard text can be automatically changed with following command ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)):

```ini
[Command]
Automatic=true
Command="
    copyq:
    var text = str(input())
    if ( text.indexOf('_') == -1 )
        abort()
        
    var newText = text.replace(/_/g, ' ')
    setData(mimeText, newText)
    removeData(mimeHtml)
    copy(newText)"
Icon=\xf15b
Input=text/plain
Name=Replace Underscores
```

But it would be definitely better to add more specific matching because the above would break copied URLs and code.
