### ISSUE TITLE
Can I choose the font foreground color and the font background color for tabs in CopyQ?

### ISSUE THREAD

**Issue by Raytle** [hluk/CopyQ#1713]
Can I choose the font foreground color and the font background color for tabs in CopyQ?

![Image 1](https://user-images.githubusercontent.com/81956552/125780949-7f6390a0-7d3a-4ba2-91c9-7a5f11484696.png)

**Comment by hluk** [comment]
To set background color for the tabs:

1. Go to Appearance tab in Preferences dialog.
2. Enable "Set colors for tabs, tool bar and menus" option.
3. Click Edit Theme button.
4. Change `background: ...` under `tab_bar_tab_unselected_css="...`:
```
    ;background: #84ccce"
```
5. Change `background: ...` under `tab_bar_tab_selected_css="...`:
```
    ;background: #9cf09d
```
6. Save file and click OK in Preferences dialog.

Sometimes you need to restart the app for the theme changes to take effect and fully override system theme.

**Comment by Yekutiel** [comment]
Thanks for taking the time to explain that to me.

> To set background color for the tabs:
> 
> 1. Go to Appearance tab in Preferences dialog.
> 2. Enable "Set colors for tabs, tool bar and menus" option.
> 3. Click Edit Theme button.

When I clicked the `Edit Theme` button **nothing happened**. Therefore I tried the following...

1. I found `tab_bar_tab_unselected_css` located in  `~.config/copyq/themes/main_window.css` but,
2.  not in `~config/copyq/themes/solarized-light.ini`

What should I do?

## Feature Suggestion
Here's a feature suggestion (which I think I might have made previously): when the user right mouse clicks on a tab they will have an option to change the color of the tab.

The following example comes from Google Sheets (which is the name of Google's cloud-based spreadsheet) but it probably could have come from Microsoft Excel or many other spreadsheets...

![Image-01](https://user-images.githubusercontent.com/16394972/126959256-558e7a75-92b6-40cd-ba15-fcdd509a9fb9.png)

**Comment by Raytle** [comment]
Thanks for taking the time to explain that to me.

> To set background color for the tabs:
> 
> 1. Go to Appearance tab in Preferences dialog.
> 2. Enable "Set colors for tabs, tool bar and menus" option.
> 3. Click Edit Theme button.

When I clicked the `Edit Theme` button **nothing happened**. Therefore I tried the following...

1. I found `tab_bar_tab_unselected_css` located in  `~.config/copyq/themes/main_window.css` but,
2.  not in `~config/copyq/themes/solarized-light.ini`

What should I do?

## Feature Suggestion
Here's a feature suggestion (which I think I might have made previously): when the user right mouse clicks on a tab they will have an option to change the color of the tab.

The following example comes from Google Sheets (which is the name of Google's cloud-based spreadsheet) but it probably could have come from Microsoft Excel or many other spreadsheets...

![Image-01](https://user-images.githubusercontent.com/16394972/126959256-558e7a75-92b6-40cd-ba15-fcdd509a9fb9.png)

**Comment by hluk** [comment]
> When I clicked the `Edit Theme` button **nothing happened**. Therefore I tried the following...

Interesting, I would expect CopyQ to complain at least that the external editor is not set - perhaps it is not configured properly.

>     1. I found `tab_bar_tab_unselected_css` located in  `~.config/copyq/themes/main_window.css` but,
> 
>     2. not in `~config/copyq/themes/solarized-light.ini`

Current theme is in `~/.config/copyq/copyq.conf` under `[Theme]` group, but it would be a bit more difficult to edit since it contains `\n` instead of line breaks, and you need to close the app first to edit the file.

---

Marking tabs with different color could be useful. Currently, the closest thing is perhaps setting an icon for a tab.

**Comment by Yekutiel** [comment]
Thanks for taking the time to explain that to me.

> Marking tabs with different color could be useful. 

Ummmm. Hmmm. That's like asserting building round wheels for bicycles and cars could be more useful than square wheels. The features spreadsheets commonly employ for enabling users to change the color of tabs is obviously useful.

This is not an ingenious insight of mine. Not at all. I suppose it's common knowledge among millions of users who regularly use spreadsheets. Please see [colored tabs in a spreadsheet](https://www.google.com/search?q=colored+tabs+in+a+spreadsheet&sxsrf=ALeKk03e_Hdw3Pv9Z5gUMMm9_I_hiAuGBw:1627335557898&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjCgO-u2YHyAhUYvJ4KHY3bBPcQ_AUoAXoECAEQAw&biw=1535&bih=806).

Expecting ordinary users to edit something like the following, of course, would be unreasonable...

![Image 1](https://user-images.githubusercontent.com/16394972/127062260-8f40ec03-9a4f-4262-b68a-5c8a038f8946.png)

> Currently, the closest thing is perhaps setting an icon for a tab.

Yes. I know.

**Comment by Raytle** [comment]
Thanks for taking the time to explain that to me.

> Marking tabs with different color could be useful. 

Ummmm. Hmmm. That's like asserting building round wheels for bicycles and cars could be more useful than square wheels. The features spreadsheets commonly employ for enabling users to change the color of tabs is obviously useful.

This is not an ingenious insight of mine. Not at all. I suppose it's common knowledge among millions of users who regularly use spreadsheets. Please see [colored tabs in a spreadsheet](https://www.google.com/search?q=colored+tabs+in+a+spreadsheet&sxsrf=ALeKk03e_Hdw3Pv9Z5gUMMm9_I_hiAuGBw:1627335557898&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjCgO-u2YHyAhUYvJ4KHY3bBPcQ_AUoAXoECAEQAw&biw=1535&bih=806).

Expecting ordinary users to edit something like the following, of course, would be unreasonable...

![Image 1](https://user-images.githubusercontent.com/16394972/127062260-8f40ec03-9a4f-4262-b68a-5c8a038f8946.png)

> Currently, the closest thing is perhaps setting an icon for a tab.

Yes. I know.

**Comment by hluk** [comment]
> Ummmm. Hmmm. That's like asserting building round wheels for bicycles and cars could be more useful than square wheels. The features spreadsheets commonly employ for enabling users to change the color of tabs is obviously useful.

I feel like you are always mocking me. I never used tab colors and I don't think I ever needed it. I don't see how it is "obviously useful" unless you are used to the feature for specific scenarios.

> Expecting ordinary users to edit something like the following, of course, would be unreasonable...

Editing theme file (or style sheets) is the only supported way to make specific theme changes. I'm not planning to extend the configuration in Appearance tab.

To make the theme file editing easier, you can check the "External editor command" option in History tab in Preferences.

**Comment by Yekutiel** [comment]
> > Ummmm. Hmmm. That's like asserting building round wheels for bicycles and cars could be more useful than square wheels. The features spreadsheets commonly employ for enabling users to change the color of tabs is obviously useful.
> 
> I feel like you are always mocking me. I never used tab colors and I don't think I ever needed it. I don't see how it is "obviously useful" unless you are used to the feature for specific scenarios.

I am not mocking you; I am trying to point out the absurdity of many of your assertions.

Unbeknownst to them, most engineers—a category which subsumes software developers—are bad at [usability engineering](https://www.interaction-design.org/literature/topics/usability-engineering). I think I sent you this before, but in case I didn't please read...

> [This Is What Happens When You Let Developers Create UI](https://blog.codinghorror.com/this-is-what-happens-when-you-let-developers-create-ui/)

> "Deep down inside every software developer, there's a budding graphic designer waiting to get out. And if you let that happen, you're in trouble. Or at least your users will be, anyway..."

CopyQ has many excellent features yet a poor user interface: very poor user interface. 

Engineers typically relish complaining about absurd user requests. See, for example, this cartoon showing how [a user claims that fixing a problem breaks his workflow](https://xkcd.com/1172/) or [asking for these two features](https://xkcd.com/1425/) one which is trivial and one which is extremely difficult.


> > Expecting ordinary users to edit something like the following, of course, would be unreasonable...
> 
> Editing theme file (or style sheets) is the only supported way to make specific theme changes. I'm not planning to extend the configuration in Appearance tab.

Why not? CopyQ has a very nice feature that almost zero ordinary users will likely ever use because of its arcane design.

If you think, "I made CopyQ for me. If people like it then that is good. On the other hand, if they don't like CopyQ, then that is too bad for them." feel free to let me know and I won't squander my time making suggestions. I'm serious. You are not the first FOSS developer I've dealt with. You guys tend to be of the same ilk: self-righteous, tone deaf, builders who don't care much about users. Frankly, it is one of the reasons that most people tend to dislike nerds. Jeff Bezos thought he would be heralded as a hero instead of mocked as a modern-day robber baron for his recent flight into the heavens which is similar to CopyQ in many ways: both were built to primarily to satisfy an engineer, not to actually help ordinary people.

If Jeff Bezos (and Elon Musk) wanted to help people they could simply increase wages they paid to their employees and treat them better. Similarly, if you actually cared about helping ordinary users of CopyQ, then you would focus on creating a better user interface design.


> To make the theme file editing easier, you can check the "External editor command" option in History tab in Preferences.

If I told you I was going to travel from London to Paris via the South Pole what would you say? Sure. It could be done. But why do it? Normally that would be an absurd route. CopyQ violates many of the extremely common [best practices](https://en.wikipedia.org/wiki/Best_practice) for UI/UX (user interface/user experience design).

Just as it would normally be absurd to travel from London to Paris via the South Pole, if you actually want to help ordinary users, you should not expect ordinary users to follow arcane instructions to achieve mundane tasks. In this case, CopyQ solves a "solved problem" in a way that an ordinary user would probably find utterly, totally, and completely absurd. Saying, "Yeah, I should put it on my 'Needs a Conventional User Interface ToDo List' would be reasonable. But saying, 'I am not going to fix it' suggests a selfish FOSS demi-god indie developer who doesn't care much about ordinary users."

And. Oh yeah. All that time you spend squandering helping users to figure our CopyQ's arcane system which, of course, probably makes sense to you. I've encountered that ego-driven "hero behavior" many times among selfish FOSS demi-god indie developers. You guys typically enjoy being  heroes, yet neither want to bother creating proper user interfaces nor proper documentation.

Using science to actually help ordinary people typically hardly actually matter to you guys. What matters? Your own egos! Oh the plethora—or perhaps plague—of closed-minded, hypocritical "men of science" disgusts me.

Read, watch, and learn...

> This from the same Steve Jobs who famously said in 1996: "Picasso had a saying -- 'good artists copy; great artists steal' -- and we have always been shameless about stealing great ideas." [What Steve Jobs really meant when he said 'Good artists copy; great artists steal'](https://www.cnet.com/news/what-steve-jobs-really-meant-when-he-said-good-artists-copy-great-artists-steal/)

Stop trying to [reinvent the wheel](https://en.wiktionary.org/wiki/reinvent_the_wheel#:~:text=(idiomatic)%20To%20do%20work%20unnecessarily,when%20a%20solution%20already%20exists.). Instead, copy existing elegant solutions.

Engineers and scientists typically aspire to be like Newton or Tesla or Einstein. But to my mind, it's usually much more valuable to be like Edison or Jobs or Zuckerberg. By which I mean: don't invent; instead merely copy. The plethora of clever engineers and scientists who fritter away their time proudly inventing solutions that are worse than readily available, existing solutions disgusts me.

For example, PhD candidates normally must first do a "review of the literature" before their dissertation topic will be approved. Why? Primarily this prevents them from solving a problem that had been previously solved.

Stop trying to be a genius inventor and start being a copycat. Yeah. I know. It's more fun for engineers to be geniuses than copycats. But. Well. Here's the thing. It's not 1971; it's 2021. During those last 50 years so much great stuff has been invented for desktop, laptop, and now "pocket" computers (Androids and iPhones) that the work that needs to be done is applying those inventions practically to solve real problems that real users actually have.

This, of course, frustrates some billionaires who seem themselves as "geniuses." Therefore, they have deluded themselves into thinking that space travel is a worthwhile endeavor for them to focus their "ingenious" energies on.

Jon Stewart recently pilloried these arrogant fools in [The Problem With Jon Stewart | The Problem With Dicks In Space](https://youtu.be/3LPiM9d5QUM?t=95).

**Comment by Raytle** [comment]
> > Ummmm. Hmmm. That's like asserting building round wheels for bicycles and cars could be more useful than square wheels. The features spreadsheets commonly employ for enabling users to change the color of tabs is obviously useful.
> 
> I feel like you are always mocking me. I never used tab colors and I don't think I ever needed it. I don't see how it is "obviously useful" unless you are used to the feature for specific scenarios.

I am not mocking you; I am trying to point out the absurdity of many of your assertions.

Unbeknownst to them, most engineers—a category which subsumes software developers—are bad at [usability engineering](https://www.interaction-design.org/literature/topics/usability-engineering). I think I sent you this before, but in case I didn't please read...

> [This Is What Happens When You Let Developers Create UI](https://blog.codinghorror.com/this-is-what-happens-when-you-let-developers-create-ui/)

> "Deep down inside every software developer, there's a budding graphic designer waiting to get out. And if you let that happen, you're in trouble. Or at least your users will be, anyway..."

CopyQ has many excellent features yet a poor user interface: very poor user interface. 

Engineers typically relish complaining about absurd user requests. See, for example, this cartoon showing how [a user claims that fixing a problem breaks his workflow](https://xkcd.com/1172/) or [asking for these two features](https://xkcd.com/1425/) one which is trivial and one which is extremely difficult.


> > Expecting ordinary users to edit something like the following, of course, would be unreasonable...
> 
> Editing theme file (or style sheets) is the only supported way to make specific theme changes. I'm not planning to extend the configuration in Appearance tab.

Why not? CopyQ has a very nice feature that almost zero ordinary users will likely ever use because of its arcane design.

If you think, "I made CopyQ for me. If people like it then that is good. On the other hand, if they don't like CopyQ, then that is too bad for them." feel free to let me know and I won't squander my time making suggestions. I'm serious. You are not the first FOSS developer I've dealt with. You guys tend to be of the same ilk: self-righteous, tone deaf, builders who don't care much about users. Frankly, it is one of the reasons that most people tend to dislike nerds. Jeff Bezos thought he would be heralded as a hero instead of mocked as a modern-day robber baron for his recent flight into the heavens which is similar to CopyQ in many ways: both were built to primarily to satisfy an engineer, not to actually help ordinary people.

If Jeff Bezos (and Elon Musk) wanted to help people they could simply increase wages they paid to their employees and treat them better. Similarly, if you actually cared about helping ordinary users of CopyQ, then you would focus on creating a better user interface design.


> To make the theme file editing easier, you can check the "External editor command" option in History tab in Preferences.

If I told you I was going to travel from London to Paris via the South Pole what would you say? Sure. It could be done. But why do it? Normally that would be an absurd route. CopyQ violates many of the extremely common [best practices](https://en.wikipedia.org/wiki/Best_practice) for UI/UX (user interface/user experience design).

Just as it would normally be absurd to travel from London to Paris via the South Pole, if you actually want to help ordinary users, you should not expect ordinary users to follow arcane instructions to achieve mundane tasks. In this case, CopyQ solves a "solved problem" in a way that an ordinary user would probably find utterly, totally, and completely absurd. Saying, "Yeah, I should put it on my 'Needs a Conventional User Interface ToDo List' would be reasonable. But saying, 'I am not going to fix it' suggests a selfish FOSS demi-god indie developer who doesn't care much about ordinary users."

And. Oh yeah. All that time you spend squandering helping users to figure our CopyQ's arcane system which, of course, probably makes sense to you. I've encountered that ego-driven "hero behavior" many times among selfish FOSS demi-god indie developers. You guys typically enjoy being  heroes, yet neither want to bother creating proper user interfaces nor proper documentation.

Using science to actually help ordinary people typically hardly actually matter to you guys. What matters? Your own egos! Oh the plethora—or perhaps plague—of closed-minded, hypocritical "men of science" disgusts me.

Read, watch, and learn...

> This from the same Steve Jobs who famously said in 1996: "Picasso had a saying -- 'good artists copy; great artists steal' -- and we have always been shameless about stealing great ideas." [What Steve Jobs really meant when he said 'Good artists copy; great artists steal'](https://www.cnet.com/news/what-steve-jobs-really-meant-when-he-said-good-artists-copy-great-artists-steal/)

Stop trying to [reinvent the wheel](https://en.wiktionary.org/wiki/reinvent_the_wheel#:~:text=(idiomatic)%20To%20do%20work%20unnecessarily,when%20a%20solution%20already%20exists.). Instead, copy existing elegant solutions.

Engineers and scientists typically aspire to be like Newton or Tesla or Einstein. But to my mind, it's usually much more valuable to be like Edison or Jobs or Zuckerberg. By which I mean: don't invent; instead merely copy. The plethora of clever engineers and scientists who fritter away their time proudly inventing solutions that are worse than readily available, existing solutions disgusts me.

For example, PhD candidates normally must first do a "review of the literature" before their dissertation topic will be approved. Why? Primarily this prevents them from solving a problem that had been previously solved.

Stop trying to be a genius inventor and start being a copycat. Yeah. I know. It's more fun for engineers to be geniuses than copycats. But. Well. Here's the thing. It's not 1971; it's 2021. During those last 50 years so much great stuff has been invented for desktop, laptop, and now "pocket" computers (Androids and iPhones) that the work that needs to be done is applying those inventions practically to solve real problems that real users actually have.

This, of course, frustrates some billionaires who seem themselves as "geniuses." Therefore, they have deluded themselves into thinking that space travel is a worthwhile endeavor for them to focus their "ingenious" energies on.

Jon Stewart recently pilloried these arrogant fools in [The Problem With Jon Stewart | The Problem With Dicks In Space](https://youtu.be/3LPiM9d5QUM?t=95).

**Comment by hluk** [comment]
These conversations get of topic fast. I'm closing this.

**Comment by Raytle** [comment]
That's an ignorant response.
