### ISSUE TITLE
X11 Clipboard gets cleared when app closes

### ISSUE THREAD

**Issue by ArtyIF** [hluk/CopyQ#1762]
**Describe the bug**
When an app that put an item in clipboard closes, the clipboard content gets cleared. The item's still accessible and selectable in CopyQ itself, but it does need to be selected before it could be used again.

**To Reproduce**
1. Copy something in an app
2. Close the app
3. Try pasting it
4. Clipboard is empty, and you have to open CopyQ and select the item to paste it
A great command to demonstrate it (and the one I'm having issues with) is `spectacle --background --copy-image --current`. The program closes after around 5 seconds, and while the screenshot stays in CopyQ, I need to select it manually to paste it somewhere after those 5 seconds pass.

**Expected behavior**
The item stays selected in the clipboard after closing the app.

**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - Application Version: v4.1.0
 - OS: Arch Linux
 - Desktop environment, window manager: `awesome v4.3-1147-g5ca16ae8a`

**Additional context**

**Comment by hluk** [comment]
This is normal behavior on X11 - closing X11 clipboard owner means that the clipboard content will no longer be accessible.

You can add [Reset Empty Clipboard/Selection](https://github.com/hluk/copyq-commands/tree/master/Scripts#reset-empty-clipboardselection) command to CopyQ so that it tries to avoid this situation (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command).
