### ISSUE TITLE
Bug # 1216 09/11/19 is back since version 4

### ISSUE THREAD

**Issue by Ragista** [hluk/CopyQ#1768]
**Describe the bug**
When the mouse is at the edge of the screen, the hotkey "show main window under mouse cursor" usually opens the Copy Q window outside of the screen. Does "Fix sanitizing window position" no longer work?

**To Reproduce**
1. Mouse on the right edge (or the bottom) of the screen
2. Press the Hotkey for "show main window under mouse cursor"
3. CopyQ Window is outside the screen

**Expected behavior**
CopyQ window is completely visible

**Screenshots**

**Version, OS and Environment**
Windows 10, CopyQ 4.1 and 5.0
![copyqbug](https://user-images.githubusercontent.com/55202211/135500714-914c7e45-baa6-44f0-ad6b-fcc394355559.jpg)

**Comment by hluk** [comment]
I don't see any changes that would affect this since the fix was implemented, but it's quite possible that something has changed in recent Qt versions (there were a lots of high-DPI fixes).

Do you use some scaling in Windows?

Do you have a multi-monitor layout?

Can you share debug logs? Here is how to enable it: https://copyq.readthedocs.io/en/latest/faq.html#how-to-enable-logging

**Comment by Ragista** [comment]
Hello Lukas, thank you very much for the answer. I only have a 4K monitor with 175% scaling. And really, if I switch to 100% the bug disappears. A small part of the window is outside at the bottom, but that's ok. So it is probably due to QT. I attach a log file.
[copyq.log](https://github.com/hluk/CopyQ/files/7267652/copyq.log)

**Comment by hluk** [comment]
I think it's now caused by this fix: a7d1609dc266720a6520117f0edf88d74566cb86

It might have been broken only with a specific Qt version or in some desktop environment. I'll try to revert the change and test.

**Comment by hluk** [comment]
@Ragista Can you test the fix with [this development version](https://ci.appveyor.com/project/hluk/copyq/builds/40988202/job/6jexvpv303m7nhu3/artifacts)?

**Comment by Ragista** [comment]
A small part of the window is missing, but that's ok. The bug is fixed. Thank you, good job
![copyqbug2](https://user-images.githubusercontent.com/55202211/135650321-ff905802-15f2-4c55-810e-09ba2b692523.jpg)

**Comment by hluk** [comment]
> A small part of the window is missing

Can you check with [a newer development version](https://ci.appveyor.com/project/hluk/copyq/builds/40995264/job/2hsm3l5dr4sqptm7/artifacts)? It's probably caused by the window frame (+title) geometry not being included. Unfortunaly, the fix may not work in some situations because Qt cannot figure out the frame size before the window shows up for the first time (this has been a long standing issue in Qt).

**Comment by Ragista** [comment]
Hello Lukas, the problem has been completely eliminated in the new version. The window is completely visible. The problem is solved.

**Comment by hluk** [comment]
Glad to hear it works now. Feel free to use the dev version until the next release (the dev version only contains the window geometry fixes applied to the recent version 5.0.0).
