### ISSUE TITLE
FR: Play a short sound when item successfully copied to the clipboard

### ISSUE THREAD

**Issue by Gitoffthelawn** [hluk/CopyQ#1865]
**Is your feature request related to a problem? Please describe.**
Every once in a while, it seems that pressing Ctrl+C does not copy clipboard text into CopyQ.  Although, IIRC, this has been reported, sometimes I wonder if it's user error (thinking you pressed Ctrl+C when you really pressed adjacent keys). 

**Describe the solution you'd like**
It would be great if CopyQ could play a *very* short sound when the user copies text to the clipboard (optional, of course).

**Describe alternatives you've considered**
I've considered writing a command to run an external executable on every copy operation to play a sound.  But I think for such a frequent operation as copying text to the clipboard, it would be better if CopyQ handles this internally.  This will avoid disk read operations and other sources of lag to play the sound as the item is copied to the clipboard/CopyQ.

**Comment by hluk** [comment]
This has been already discussed here: #1328

**Comment by Gitoffthelawn** [comment]
Thank you Lukas.  Added a note in #1328.  Closing this issue now.

**Comment by Chealer** [comment]
Thank you for reporting @Gitoffthelawn 

With CopyQ 13.0, by default, a sound is played on Windows (11). This is because a native notification is triggered, and Windows (by default) plays a sound for notifications.

Unfortunately, I would not qualify that sound as "short". ClipClip plays a much shorter sound, which is better, since copying is a very banal event. It is also better to have a distinct sound, so it cannot be confused with another notification.

<details>
  <summary>License</summary>
This comment and any other from myself on this ticket is offered under the terms of CC0 1.0.
</details>

**Comment by Gitoffthelawn** [comment]
> Thank you for reporting [@Gitoffthelawn](https://github.com/Gitoffthelawn)

You're welcome.

> With CopyQ 13.0, by default, a sound is played on Windows (11). This is because a native notification is triggered, and Windows (by default) plays a sound for notifications.

I find CopyQ to be much more useful with it's custom notifications.  Win11 notifications are slow, bulky, monochromatic.  Plus, CopyQ notifications, by design, are frequent and thus detract from the other purposes of the Windows Notifications system.

> Unfortunately, I would not qualify that sound as "short". ClipClip plays a much shorter sound, which is better, since copying is a very banal event. It is also better to have a distinct sound, so it cannot be confused with another notification.

Yes, definitely!

**Comment by Chealer** [comment]
As of CopyQ 13, customizing the sound requires a custom command. [The documentation explains](https://github.com/hluk/CopyQ/wiki/Command-Examples#play-sound-when-copying-to-clipboard) how to create one for GNU systems and Microsoft Windows.
