### ISSUE TITLE
Command Duplicate 

### ISSUE THREAD

**Issue by alabotski** [hluk/CopyQ#1932]
It's very old bug 
Version 6.1.0
For some reason, I have duplicate commands

Пометить как "Важный"
Удалить метку "Важный"
and english

Tag as "Important"
Remove tag "Important"

I tried to remove the English names, but for some reason they still return

![image](https://user-images.githubusercontent.com/439337/158059731-d9c482a2-9231-43aa-b4be-24063ff2ecdb.png)

**Comment by hluk** [comment]
Those commands are added depending on app configuration. The way this happens has been changed in 6.0.0:

> Internal commands (like ""Show/hide main window", Pin/Unpin, Encrypt/Decrypt)
will now be automatically updated in following application releases or
whenever the language changes. The side-effect is that only icon, shortcuts,
enabled state and list order can be changed for these commands. Old internal
commands added in previous versions (5.0.0 and lower) of the app need to be
removed manually.

The fix is to remove the old commands.

If you do not want to see these Tag commands, you can either disable the Tag plugin completely or remove the Important tag from configuration (it is under Item in Preferences dialog).
