### ISSUE TITLE
Upgraded to Ubuntu 22.04 and CopyQ short cut only works in some apps

### ISSUE THREAD

**Issue by HeRo002** [hluk/CopyQ#2062]
Hi!

I am a very happy daily user of CopyQ. I invoke it with a custom keyboard short cut: Ctrl-Æ. 

Now I have upgraded my Ubuntu 20.04.1 LTS to Ubuntu 22.04.1 LTS. But now Ctrl-Æ only works in some apps... It works in Firefox version 104.0 but not in Thunderbird version 91.11.0. It works in Kate Version 21.12.3 but not in LibreOffice Community Version: 7.2.6.2. 
Luckily I have a drive image backup of the Ubuntu partition from before the upgrade... But is there any way of making it work on Ubuntu 22.04?

**Comment by hluk** [comment]
It is probably caused by using Wayland instead of X11. See also: https://copyq.readthedocs.io/en/latest/known-issues.html#on-linux-global-shortcuts-pasting-or-clipboard-monitoring-does-not-work

Another quick solution (aside from the ones mentioned in the documentation) is to switch back to X11 Ubuntu session (on login).

**Comment by hluk** [comment]
> I am not sure how "to switch back to X11 Ubuntu session (on login)."?

Select "Gnome (X11)" or something similar in your before you log in.

**Comment by HeRo002** [comment]
That works! 
Before logging in, I can choose between "Ubuntu" and "Ubuntu on Xorg". When I choose "Ubuntu on Xorg" the short cut key for opening CopyQ - Ctrl-Æ - works in all apps (so far). :-) 

PS: In my message above, the line - Exec="/usr/bin/copyq" - is supposed to be commented out with the 'hashtag' character. But here in this editor that character means headline...

**Comment by fade2gray** [comment]
@HeRo002  [How to use `Markdown` to quote code on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).

```
Exec=env QT_QPA_PLATFORM=xcb copyq
# Exec="/usr/bin/copyq"
```

**Comment by Huehnerbrust** [comment]
Hi all,

I just installed copyq because I was looking for a linux ditto-like app.

On ubuntu 22.04.02 LTS with wayland, is there any option to get copyq running correctly? On my system copyq does not open when using it in e.g., libreoffice writer.

I tried the above: Exec=env QT_QPA_PLATFORM=xcb copyq
That did not help...


Thanks!
