### ISSUE TITLE
Versions 6.3.1 & 6.3.2 do not run on macOS 10.15

### ISSUE THREAD

**Issue by kalitara** [hluk/CopyQ#2103]
**Describe the bug**
Versions 6.3.1 and 6.3.2 do not run on Catalina / Intel based Macs.

**To Reproduce**
Download DMG
Open DMG in the Finder
Notice that CopyQ app icon has a circle with line icon covering it in the finder.
Running the app from here or from the Application folder produces an alert that the app can not run on this OS.

**Expected behavior**
The app would be allowed to run.

**Screenshots**
https://drive.google.com/file/d/1dDIx5eoCH2LSqfewhVWvBg_i-E3fZQaa/view?usp=sharing

**Version, OS and Environment**
CopyQ version: 6.3.1 or 6.3.2
MacOS version: Catalina 10.15.7

**Additional context**

**Comment by hluk** [comment]
I had to use newer the GitHub Actions runner image for building the app for macOS (0d0128dbe337ce9b1fb6359f85c048ca75b36190) because the 10.15 image is deprecated and no longer works: https://github.com/actions/runner-images/issues/5583

Unfortunately, I'm not sure if something can be done about the compatibility with macOS 10.15.

**Comment by hluk** [comment]
Can you test [this build](https://github.com/hluk/CopyQ/actions/runs/3122601119#artifacts)?

**Comment by kalitara** [comment]
> Can you test [this build](https://github.com/hluk/CopyQ/actions/runs/3122601119#artifacts)?

This build works for me.

**Comment by hluk** [comment]
> > Can you test [this build](https://github.com/hluk/CopyQ/actions/runs/3122601119#artifacts)?
> 
> This build works for me.

I will merge the fix and update the macOS build in 6.3.2 release.

Thanks for testing and your report!
