### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by xcasxcursex** [hluk/CopyQ#2214]
**Is your feature request related to a problem? Please describe.**
I wanted to switch from ditto to a cross-platform clipboard manager, so I tried this, and the performance was not great.

**Describe the solution you'd like**
Near-zero CPU usage and memory usage, no limit on database. ie, this has been running for days with a database gigabytes in size: 
![image](https://user-images.githubusercontent.com/58130821/209757763-5f0011f4-0aa5-4a4e-a35c-76d1e4c0d9e7.png)

**Describe alternatives you've considered**
Crying because I won't be able to switch to linux without a good clipboard manager. I read threads here about the database size limit and I know about infinitecopy, I'll keep an eye on it.

**Additional context**
Aside from performance I really liked copyq!

**Comment by hluk** [comment]
You would need to be more specific. I do not see any performance issues with CopyQ.

**Comment by xcasxcursex** [comment]
> You would need to be more specific. 

Constant CPU usage regardless of clipboard (in)activity, high and growing memory usage, tied to search times (I've seen this brought up in relation to database size limits)

> I do not see any performance issues with CopyQ.

Do you see the kind of performance I'm seeing in ditto as pictured and described above? Perhaps there was something wrong when I ran copyq on my PC, but it didn't behave like that.

**Comment by hluk** [comment]
> Constant CPU usage regardless of clipboard (in)activity, high and growing memory usage, tied to search times (I've seen this brought up in relation to database size limits)

The memory usage is probably higher because it uses large Qt framework and can keep a lot of clipboard items in memory (usually the whole clipboard tab).

On the other hand the app should not be processing anything when idle (unless you use some custom commands that do work in background).

It would be better if you can share **logs** and more **performance details related to CopyQ**.

**Comment by pallaswept** [comment]
> > Constant CPU usage regardless of clipboard (in)activity, high and growing memory usage

I also noticed this when I was on windows, and used ditto instead, as did OP. Sorry I never got any data from copyq when I was on windows, I just took the faster option and moved on....

I have switched to linux (openSUSE KDE Wayland) and tried copyq (it works much better than KDE's built-in clipboard manager and of course is WAY more powerful and flexible) - the performance is exceptional. I don't see any of the kind of behaviour I saw on windows - even with the maximum history cranked to the maximum 10000 and a handful of custom commands. 

None of the problems I saw on windows exist here: Memory usage is low, _doesn't grow_, and CPU usage is _zero_ unless it's doing something and then it's near zero anyway. 

I thought this might be interesting for you to know, that performance is so different on the different OS. Since OP described my issues on windows exactly, I thought I'd reply to this issue instead of making a new one. I hope the info is useful to you and thank you for an outstanding clipboard manager.
