### ISSUE TITLE
hardlink to copyq.ini overwritten with vanilla file in Win10

### ISSUE THREAD

**Issue by jmlucjav** [hluk/CopyQ#2230]
**Describe the bug**
I like to keep my config files (copyq.ini etc) in a central dir, in my case synched via dropbox.  So I replace the file C:\Users\xx\AppData\Roaming\copyq\copyq.ini with a hardklink to C:\somethingelse\copyq\copyq.ini.
But this hardlink is overwritten with a vanilla file when preferences are changed (or other events I guess)

**To Reproduce**
Steps to reproduce the behavior on win 10:
1. Stop copy
2. del /F /Q "%USERPROFILE%\AppData\Roaming\copyq\copyq.ini"
3. mklink /h %USERPROFILE%\AppData\Roaming\copyq\copyq.ini C:\temp\copyq.ini
4. Start copyq
5. verify %USERPROFILE%\AppData\Roaming\copyq\copyq.ini  is still a hardlink: fsutil.exe hardlink list C:\temp\copyq.ini
6. change some preference in copyq, so it persists it
7. now verify %USERPROFILE%\AppData\Roaming\copyq\copyq.ini  is a normal file, different to the other one: fsutil.exe hardlink list C:\temp\copyq.ini

**Expected behavior**
The hardlink should be used as expected

coy**Version, OS and Environment**
(Get details from `copyq version` command if possible.)
 - 6.3.2
 - win10 22H2

I am trying to move from Ditto to this tool, looks very promising, thanks for the good work!

**Comment by hluk** [comment]
CopyQ internally backs up and restores the configuration because there were some issues with handling it safely with Qt framework in the past. So linking or sharing the configuration is not supported.

I can try removing this workaround since Qt has quite possibly fixed most of the issues (so losing configuration is less likely) but linking the config file won't be officially supported since there can be cases where the file is replaced.

**Comment by jmlucjav** [comment]
Sure, if you change this I will give it a go and report. I do this with many apps and never had any real issue that I recall...
Thanks!

**Comment by hluk** [comment]
Patch removing the settings workaround is in #2237. Let's discuss there.

The latest development build for Windows: https://ci.appveyor.com/project/hluk/copyq/builds/45985448/artifacts
