### ISSUE TITLE
Windows 11 Pro 22H2 Show/hide main window shortcut doesn't work with § key/character

### ISSUE THREAD

**Issue by Marcurling** [hluk/CopyQ#2406]
**Describe the bug**
Windows 11 Pro 22H2 Show/hide main window shortcut doesn't work : it simply type the § character you assigned to present window (CopyQ or other Program).

**To Reproduce**
1. Go to 'Preferences/Shorcuts'
2. Assign a key to 'Show/hide main window'
3. Button 'Apply' and/or 'OK'
4. Type your shortcut key : it appears intead Showing/hide main window. (e.g. §)

**Version, OS and Environment**
 - Application Version 7.0.0
 - OS Windows 11 Pro 22H2
 - French environment/Keyboard (AZERTY)

**Additional context**
Other functions or keys works perfectly :)
Only some keys doesnt work like § or µ

**Comment by hluk** [comment]
Is the problem assigning the shortcut or triggering it when assigned?

**Comment by hluk** [comment]
> The problem does NOT occur on special Win 11 Pro Spectre where the
shortcuts appears as Shift+! instead of § for the previouses (it is the
same key on AZerty / French keyboard).

This is probably a problem in the Qt framework which the app uses to capture shortcuts.

It is possible to edit the shortcut manually:

1. Open Commands dialog - F6 shortcut from the main window.
2. Select "Show/hide main window" command from the list on the left.
3. Click "Copy Selected" button (or Ctrl+C) to copy the command to clipboard.
4. Go back to the item list in the main window.
5. Paste the command into the list (Shift+Insert or Ctrl+V).
6. Edit the item - F2 shortcut.
7. Change the value of `GlobalShortcut=...` line to the shortcut you need.
8. Save the item (from toolbar or F2 again).
9. Copy the changed item back to clipboard (Ctrl+C).
10. Go to Commands dialog.
11. Remove the old "Show/hide main window" command from the list (with "Remove" button above the list).
12. Paste the changed command from clipboard with "Paste Commands" button.
13. Save with OK.

**Comment by Marcurling** [comment]
It does NOT work with § (Shift+!) in AZerty
BUT I found an interesting alternative shortcut as Alt+² (which is located
aboce the Tabulation key in the French keyboard).
Thanks for your concern, kind regards, Marc.

Le lun. 4 sept. 2023 à 16:56, Lukas Holecek ***@***.***> a
écrit :

**Comment by hluk** [comment]
Few Qt issues related to this:
- [QTBUG-114624](https://bugreports.qt.io/browse/QTBUG-114624)
- [QTBUG-58304](https://bugreports.qt.io/browse/QTBUG-58304)

It is possible that this is alredy fixed in newer version of Qt. Unfortunately, the service I use to build the binaries for Windows has an older Qt version.

It also could be fixed by moving to Qt 6 but that version is not yet supported by other libraries.

**Comment by hluk** [comment]
Here is portable Qt 6 version of the app if you want to try: https://ci.appveyor.com/project/hluk/copyq/builds/47953962/artifacts (it just does not support native notifications yet)

The newer version has slightly different configuration format, so it may be better to keep a backup of your current configuration files (`config/*.cfg`, `config/*.ini`).

**Comment by Chealer** [comment]
This reproduces on 1 Windows 11 Home 25H2 on 1 tested, with CopyQ 14.0.0. With the traditional AZERTY layout, I also cannot trigger. With [CAN/CSA Z243.200-92 ("Canadian Multilingual Standard")](https://en.wikipedia.org/wiki/CSA_keyboard), I cannot assign.

@hluk: Please clarify how this was completed.

<details>
  <summary>License</summary>
All comments and attachments from myself on this ticket are offered under the terms of CC0 1.0.
</details>
