### ISSUE TITLE
Why do i get "Failed to remove EXIF" all the time, when i try to paste some item?

### ISSUE THREAD

**Issue by abr0011** [hluk/CopyQ#2416]
How can i get rid of that?

**Comment by abr1926** [comment]
Can anybody assist, please?

**Comment by hluk** [comment]
Where does the message appear? What CopyQ version and OS do you use? Any steps to reproduce?

**Comment by abr1926** [comment]
It apperars quite often, but not always, when i try to paste some saved image from CopyQ, from one of the several tabs. My workaround so far is, to use the preview pane (F7), and to crop the image from there, so that i can paste it. The version is 7.0.0, in Windows 11 Pro. The initial images are screenshots, made with an dedicated screenshot tool, which is possibly doing something with those .png files. But i assume, that CopyQ should be able to paste it anyway. Thanks for your help, great tool!

**Comment by hluk** [comment]
When and where does the "Failed to remove EXIF" message appear? When copying or pasting? Is it message from CopyQ?

I cannot find the message in CopyQ nor Qt code base.

**Comment by abr1926** [comment]
Then that message must come either from the Opera browser, or the social media platform site, i am using. It happen infrequently, when pasting image clips from ShareX, which is a screenshot application. Please consider this issue as solved then, since it is not from CopyQ.
