### ISSUE TITLE
Performance needs to be improved

### ISSUE THREAD

**Issue by victorwwd** [hluk/CopyQ#2461]
**Is your feature request related to a problem? Please describe.**
When I wake up copyq, I always feel a delay, even when I install it on a solid-state drive

**Describe the solution you'd like**
I hope it can accelerate the running speed of the software

**Describe alternatives you've considered**
It may be possible to delay rendering part of the secondary menu?

**Additional context**
.

**Comment by hluk** [comment]
There are already a lot of fixes in place to make the app faster.

> It may be possible to delay rendering part of the secondary menu?

I don't think this rendering is the problem - but if so, it is a Qt bug.

In most cases the problem is opening a tab with large number of items and sometimes working with a huge items.

Not sure what should be the fix here unless you can provide more data.
