### ISSUE TITLE
Install on standard user

### ISSUE THREAD

**Issue by xmha97** [hluk/CopyQ#2656]
When the app is to be installed only for the current user, it should not be installed in "Program Files".

![image](https://github.com/hluk/CopyQ/assets/23485114/cae28a50-cfe6-4ec0-8631-3562188da2f9)

_Originally posted by @xmha97 in https://github.com/hluk/CopyQ/issues/1912#issuecomment-1546821546_

**Comment by hluk** [comment]
Sorry about this. It is a breaking change, but it is needed because 64bit applications (like the official versions of CopyQ) should be installed in "Program Files" and 32bit apps to "Program Files (x86)".

After installing the new version (to the correct location), you may need to remove/uninstall the app from the old path (the installer framework unfortunately does not support this).
