### ISSUE TITLE
How can I disable text/plain;charset=utf-8 ?

### ISSUE THREAD

**Issue by supply9243** [hluk/CopyQ#2779]
I copied text and sometimes can't paste it. I checked the text format and it's text/plain; charset=utf-8

It seems to be a later added feature. How can I disable it?

**Comment by JuchiaLu** [comment]
I've also come across this bug. The reason is that the textLabelForData function in [common.cpp](https://github.com/hluk/CopyQ/blob/e6895386b3526fd09dd29feced5760108471f143/src/common/common.cpp) does not check for mimeTextUtf8, resulting in MimeTextUtf8 being labeled as`<DATA>`. 

This is a temporary solution to convert MimeTextUtf8 to MimeText:

```js
[Command]
Name=MimeTextUtf8ToMimeText
Command="
    copyq:
    if(dataFormats().includes(mimeTextUtf8)){
        text = data(mimeTextUtf8)
        removeData(mimeTextUtf8)
        setData(mimeText, text)
    }"
Automatic=true
Icon=
```

**Comment by hluk** [comment]
What version of CopyQ do you use? Which OS?
