### ISSUE TITLE
Feature request: application filtering + automatic encryption

### ISSUE THREAD

**Issue by mrbeeye** [hluk/CopyQ#278]
I am new to CopyQ and not quite familiar with Tabs and Actions.

I'd like CopyQ to be able to do this:
1. ignore clipboard items (clips) from specified applications (defined by their windows title or process name),
2. rule based sorting of clips to tabs (for example: all clips from application "EXAMPLE" send to "MYTAB" tab),
3. automatic encryption of clips (for example: all clips from application "KEEPASS" encrypt and send to "SECRETS" tab).

**Comment by LinuxOnTheDesktop** [comment]
Please tell me how I can prevent credentials copied to the clipboard by the KeePass manager (which I use on Windows and, under mono, on Linux) from being copied to the CopyQ clipboard. Will your item 1 suffice for this?

Also, and if I may: is each clipboard item within CopyQ called a 'tab'? I ask because I wonder whether the option to clear tabs at a specified interval will remove the material CopyQ stores.

**Comment by hluk** [comment]
For KeePassXC on Linux, I use following command to ignore stuff copied from its window. It works well in recent CopyQ versions.

```ini
[Command]
Automatic=true
Command="
    copyq ignore"
Icon=\xf069
Name=Ignore *\"Password\"* window
Remove=true
Window=" - KeePass"
```

**Comment by LinuxOnTheDesktop** [comment]
@hluk 

Thanks. I imagine that that would work well, were it not that (1) KeePassXC hangs my machine on shutdown (a well known bugs that in my view the devs are not doing enough about), forcing me to use KeePass via mono, and were it not (2) for [this problem](https://github.com/hluk/CopyQ/issues/1179) (#1169) with CopyQ on Cinnamon.

**Comment by www-wagner** [comment]
> Please tell me how I can prevent credentials copied to the clipboard by the _KeePass_ manager (which I use on Windows and, under mono, on Linux) from being copied to the CopyQ clipboard. Will your item 1 suffice for this?

@LinuxOnTheDesktop,

I have both KeePass and KeePassXC running on Linux. I've used config like item 1, with the following regex: `- KeePass`.

On KeePassXC, it's enough because all entries are open in the main window app. **BUT** on original KeePass, it isn't enough because KeePass open new windows depending on what you are doing. For example, when you edit a entry, a new window with `Edit Entry` caption is opened and the above regex don't match with that.

So, to keep yourself safe from copy passwords or any other sensitive information to Copyq list, you have to change the regex to `- KeePass| Entry$`, ignoring all windows that has the "Entry" string at the end of the caption.

If you use any plugin that opens another window where you manage passwords (Password Change Assistant, for example), you have to include all those captions in regex to keep yourself safe! The later regex would be: `- KeePass| Entry$|^Password Change Assistant$`. And so on...

**Comment by LinuxOnTheDesktop** [comment]
@www-wagner

Thank you for the trouble that you took to write the above. However, I myself no longer use Copyq.

**Comment by hluk** [comment]
@www-wagner Thanks for sharing.

There is also a more reliable way to filter secrets from KeePassXC on Linux by checking the `x-kde-passwordManagerHint` format in clipboard: https://github.com/hluk/CopyQ/issues/1744#issuecomment-912284482

Not sure if this also works with KeePass and on other platforms. You can verify whether the format (or other special format) is in clipboard after copying a password and selecting "Show Clipboard Content" (Ctrl+Shift+C) from CopyQ.
