### ISSUE TITLE
CopyQ 9.0.0 is reporting its uinstaller as CopyQ 8.0.0

### ISSUE THREAD

**Issue by carlitorendon** [hluk/CopyQ#2855]
**Describe the bug**
Go to the uninstallers page in a manager program such as Bulk Crap Uninstaller

**To Reproduce**
Go to the registry section of uninstallers (or use Bulk Crap Uninstaller)

**Expected behavior**
Title should report version 9.x.y

**Screenshots**
![image](https://github.com/user-attachments/assets/daef78ac-5413-423f-9798-8a0638ac70a8)

**Version, OS and Environment**
CopyQ: 9.0.0
OS: Windows 11 23H2

**Comment by carlitorendon** [comment]
Notice the second to last row where the true version of the program is contained: `9.0.0`

**Comment by hluk** [comment]
Hmm, that must be a bug in Inno Setup. I see only one version variable in the config file (and it is the current version): https://github.com/hluk/CopyQ/blob/d6eb392a1b942777e243127def6403980250c491/shared/copyq.iss

**Comment by carlitorendon** [comment]
Mmm, [this](https://github.com/hluk/CopyQ/blob/d6eb392a1b942777e243127def6403980250c491/utils/view_windows_screenshots.sh#L8) is unrelated right?

**Comment by hluk** [comment]
> Mmm, [this](https://github.com/hluk/CopyQ/blob/d6eb392a1b942777e243127def6403980250c491/utils/view_windows_screenshots.sh#L8) is unrelated right?

Yup, that script only fetches screenshots for a given version from the build.

**Comment by Nagidrop** [comment]
I can confirm this isn't a CopyQ bug, but instead a bug from BCUninstaller.

I faced this issue before with JupyterLab Desktop. Even after clean uninstallation within BCUninstaller, the version of JupyterLab never changed. Likely a bug from the registry cleaning process, because re-installing Windows corrected this issue.

Here is a picture of CopyQ 9.1.0 showing correctly

![image](https://github.com/user-attachments/assets/ca0d56cc-d572-4fb1-b752-9a756c776403)

I think checking "Display Name" and "Display Version" keys inside registry path on your system could provide a hint. 

Currently I can't reproduce this issue anymore so I can't report to BCUninstaller. If you don't mind, please create a new issue on BCUninstaller's GitHub and I will be there to provide more information.

**Comment by carlitorendon** [comment]
Thank you @Nagidrop for confirming it. I guess I'll close the issue.
