### ISSUE TITLE
shortcut doesnt work when other programs are focused on the screen (tilix / firefox)

### ISSUE THREAD

**Issue by Fiehra** [hluk/CopyQ#2885]
**Describe the bug**
i have set my hide/open shortcut to alt+V
after upgrading my arch system yesterday it only sporadically works.  does NOT work when tilix (terminal emulator) or firefox are in foreground. might be more but so far these are the only ones i noticed. works when discord is main app of screen.

also while i am focusing some programs whenever i try to open copyq by using the homebutton and then searching it and opening it after it crashes/ closes rightaway without me being able to use it

**To Reproduce**
open a terminal with tilix /  open firefox
use show copyq keybind
--> nothing happens

**Expected behavior**
copyq opens

**Screenshots**

**Version, OS and Environment**
CopyQ Clipboard Manager 9.1.0
Arch: x86_64-little_endian-lp64
OS: Arch Linux

**Additional context**

**Comment by hluk** [comment]
I assume this is because of Wayland. If CopyQ is running in the X11 compatible mode, global shortcut (and other things) may not work, especially if a native Wayland app has focus.

See also:
- [FAQ: Why do global shortcuts not work?](https://copyq.readthedocs.io/en/latest/faq.html#why-do-global-shortcuts-not-work)
- [Known Issues: On Linux, global shortcuts, pasting or clipboard monitoring does not work](https://copyq.readthedocs.io/en/latest/known-issues.html#known-issue-wayland)
