### ISSUE TITLE
Checkboxes wiggle when hovered if Windows scaling is over 100%

### ISSUE THREAD

**Issue by Nagidrop** [hluk/CopyQ#2888]
**Describe the bug**

When you set Windows scaling >100% (e.g. 125%, 175%), hovering over checkboxes in CopyQ settings (preferences) will cause them to wiggle. The larger the scaling is, the more noticeable the wiggle effect.

Here is what the issue looks like on 175% scaling:

https://github.com/user-attachments/assets/95438f87-7142-459f-ad3c-da4f3c5fc685

I use only 1 monitor with fixed scaling, unlike other existing issues. I saw you mentioned Qt 5 was the culprit, but CopyQ now uses Qt 6.5, so I created a new issue here for tracking.

**To Reproduce**

1. Set Windows scaling to a value larger than 100% (e.g. 175%)
2. Go to CopyQ > Preferences
3. Hover on checkboxes

**Expected behavior**

Checkboxes don't wiggle when hovered

**Screenshots**

None

**Version, OS and Environment**

- Application Version: 9.1.0
- OS: Windows 11

**Additional context**

None

**Comment by hluk** [comment]
That is most likely a bug in the Qt framework (or desktop environment / system / system theming) since CopyQ does not handle rendering itself. I don't think I can do anything about this in the app.

As a workaround, you can try setting a different style in CopyQ:
1. Open Action dialog (F5 key)
2. Enter command `copyq: popup(styles())` to list the available styles in a popup
3. Open Action dialog again
4. Enter command `copyq config style Breeze` (where `Breeze` is a style name)
5. Restart the app (to reset the style, use `copyq config ""`)

**Comment by Nagidrop** [comment]
> That is most likely a bug in the Qt framework (or desktop environment / system / system theming) since CopyQ does not handle rendering itself. I don't think I can do anything about this in the app.
> 
> As a workaround, you can try setting a different style in CopyQ:
> 
> 1. Open Action dialog (F5 key)
> 2. Enter command `copyq: popup(styles())` to list the available styles in a popup
> 3. Open Action dialog again
> 4. Enter command `copyq config style Breeze` (where `Breeze` is a style name)
> 5. Restart the app (to reset the style, use `copyq config ""`)

Thank you for the information and workaround :D Changing the style works but the UI looks a little weird. It's only a minor issue anyway so I guess I'll live with it.
