### ISSUE TITLE
Shortcut to show clipboard content not working on Ubuntu 14.10

### ISSUE THREAD

**Issue by lepalmtree** [hluk/CopyQ#295]
Hi,

When I try to show copyq with ctrl+shift+c (or whatever shortcut I assign like ctrl+b), nothing happens.
Also, eventhough I'm using a french keyboard layout, the shortcut manager still takes my inputs as it were a qwerty keyboard. For example, when I try to assign ctrl+², it puts ctrl+`, same for ctrl+é that get ctrl+2.

I can try to give you logs if you tell me how to do it.

Regards

**Comment by lepalmtree** [comment]
I still have the problem with the latest version (2.4.4 Ubuntu 14.10 amd 64). Any idea why the shortcut isn't working ? Or how could I help you solve this issue ? I really like (and need) copyq, I use it in my everyday work.

**Comment by hluk** [comment]
You can try to edit the shortcut manually in config file.
1. Close application.
2. Open `~/.config/copyq/copyq.conf`.
3. Find `X\GlobalShortcut` option where `X` is number of the command (you can find the command name as `X\Name`).
4. Change the option value to `Ctrl+Shift+C`.

If anyone is interested in fixing the shortcut-grabbing code, you can start at [this line](https://github.com/hluk/CopyQ/blob/2cca9ea5491024ad080a4698793ddd2684ffbbcf/src/gui/shortcutdialog.cpp#L90) which retrieves `Qt::Key` from key event (it calls platform-dependent method -- [Ubuntu code](https://github.com/hluk/CopyQ/blob/2cca9ea5491024ad080a4698793ddd2684ffbbcf/src/platform/x11/x11platform.cpp#L232)).

Also note that shortcuts can be grabbed with new Qt class [QKeySequenceEdit](http://doc.qt.io/qt-5/qkeysequenceedit.html) (since Qt 5.2). But last time I checked, it didn't capture some modifiers well on X11/Linux.

**Comment by hluk** [comment]
Actually, as a workaround, you should be able to map any shortcut directly in Ubuntu preferences to run `copyq toggle` command to show/hide the application window.

**Comment by lepalmtree** [comment]
Ok thank you, I'll try this later at home

2015-01-26 12:37 GMT+01:00 Lukas Holecek <notifications@github.com>:

**Comment by lepalmtree** [comment]
It works by using Ubuntu preferences but not by modifying the .conf 
file. It'll do this way, thank you

Le lun. 26 janv. 2015 à 17:06, Hakim EL ABED <lepalmier@gmail.com> a 
écrit :
> Ok thank you, I'll try this later at home
> 
> 2015-01-26 12:37 GMT+01:00 Lukas Holecek <notifications@github.com>:
>> Actually, as a workaround, you should be able to map any shortcut 
>> directly in Ubuntu preferences to run copyq toggle command to 
>> show/hide the application window.
>> 
>> —
>> Reply to this email directly or view it on GitHub.
>> 
> 
=

**Comment by hluk** [comment]
I done some fixes for shortcuts in recent version. Though some shortcuts may still not work on some keyboard layouts.

**Comment by pablocattaneo** [comment]
> Actually, as a workaround, you should be able to map any shortcut directly in Ubuntu preferences to run copyq toggle command to show/hide the application window.

This worked for me! Thanks!
