### ISSUE TITLE
Search/filter improvements

### ISSUE THREAD

**Issue by m4r71n** [hluk/CopyQ#300]
I'm a power user of the search/filter in CopyQ so here are a few sugesstions:
- **Remember last search/filter**  
  - On main window visible the state of the last search/filter will be restored automatically. The search/filter can be canceled with `Esc`. 
- **History of searched/filtered strings**  
  - A search/filter-string will be added to the history if you hit `Enter` to select the first item, if you navigate through the results with `Up` and `Down` or by copying with `Ctrl+C`.
- **Show the history list (maybe dropdown) on `Alt+Down` if the main window is visible.**  
  - Then it will be possible to navigate with `Up` and `Down` through the history items.
  - `Enter` will apply the selected history item as current search/filter-string.
  - `Esc` will hide the history list and will not change the search/filter-string. 
  - History items can be deleted with `Shift+Delete`.
  - Optionally it will be possible to navigate through the history of the search/filter-strings by `Alt+Left` and `Alt+Right` in the main window without showing the list of history items. The current navigated search/filter-string will be directly applied as current search/filter-string
- **Better performance of search/filter**

**Comment by m4r71n** [comment]
@hluk do you have any thoughts on my suggestions?

**Comment by hluk** [comment]
Yeah, I actually tried to implement the completion the standard way (after seeing this issue), so that the completion menu pops under search field, but that get in the way too much -- you cannot see the filtered items under the menu -- that standard menu was very annoying.

I also tried to implement the item filtering the standard Qt way using [QSortFilterProxy](http://qt-project.org/doc/qt-4.8/qsortfilterproxymodel.html). Not sure what the result was but some things didn't work well -- I think I have the code saved in my local branch, so I'll check it again and perhaps push the branch to github repo for testing.

There were few situations when I needed to recall a previous search expressions. But I don't think it would be wise to store the search history by default, it could unexpectedly store some private information.

I'll try create the search history the way you describe and we'll see how it goes.

If you know any app that has really nice search/filter feature let me know.

BTW, the single most important reason I started to write clipboard manager is that no other had good filtering functionality. Now I cannot efficiently work without it :).

**Comment by hluk** [comment]
QSortFilterProxy notifies about filtered items in an inefficient way -- emits very general signal "layout changed" -- as a response to filtering I have to recreate items.

**Comment by hluk** [comment]
This was taking a bit too long so I've created `search-history` branch with simple implementation. Maybe I'll be able to come up with some good solution when using the completion.

Currently, completion list pops up if you start searching. Searches are not yet save/restored from configuration.

What needs to be done (these are quite easy):
- save history in a config file
- toggle completion in settings (clear config file if disabled?)

What should be done (possibly difficult):
- move completion menu so it doesn't hide at least first few items

**Comment by hluk** [comment]
Closing.

@m4r71n Please create new issues/feature-requests if there are any improvements needed for current search functionality.
