### ISSUE TITLE
Tab for storing clipboard...

### ISSUE THREAD

**Issue by aksr** [hluk/CopyQ#316]
Until recent commits, tab for storing clipboard was leftmost tab. It was very easy (and efficient) if you have multiple tabs to just **move** the tab to the left and it will be used. Now, I have to go to the options menu to use it. Is it possible to return this behavior in addition to the current one? Inside the menu I would put some "generics":  \<leftmost tab\> (with \> and \<), \<rightmost tab\> etc. What do you think?

**Comment by hluk** [comment]
The old behavior was that clipboard content had been automatically stored to the first tab (in tab bar and tab tree). The problem was that in tab tree the first tab could be parent/group of another tab and sometimes it was hard to tell which is the first one. Basically, ordering can be different with tab bar -- it would need to be reordered when switching from bar to tree.

The cool thing now is that you can set the "clipboard tab" option from command line using:

    copyq config clipboard_tab "&clipboard"

or in script:

    copyq:
    config("clipboard_tab", "&clipboard")

This way it's possible to change the tab for storing clipboard with global shortcut, from tray menu or from toolbar.

I can provide user command for these if you'd like.So what would be most easy way to change tab for storing clipboard?

**Comment by aksr** [comment]
Hm, I didn't know that. Shortcut is much faster than ordering (if it's the case where tab could be parent/group), - in that case, it's needed. (but) If there' no ambiguity in tabs order, I think it's faster to just move the tab to be the first (leftmost tab). In general, I think ordering should matter, but only if specifically set to matter. What do you think?

**Comment by hluk** [comment]
I won't revert the behavior, it could be confusing in some rare cases (see #303).

I thought about it and there is another solution: override the current behavior with following command (drag'n'drop or copy the code to the command list in Command dialog [F6]).

```
[Command]
Automatic=true
Command="
    copyq:
    config(\"clipboard_tab\", tab()[0])"
GlobalShortcut=DISABLED
Icon=\xf016
Name=Save Clipboard in the Left-Most Tab
```

**Comment by aksr** [comment]
This is good enough for me, thank you.
