### ISSUE TITLE
pasting dosent work in terminal

### ISSUE THREAD

**Issue by zeltak** [hluk/CopyQ#334]
Hi!

thank you for copyQ, its really an amazing app!

im not that techincal so there may be some config im not doing right but it seems that copyq dosent paste inside terminals. im sure its me not getting the hang of things. 
to describe this: issuing via hotkey copyq show > selecting entry works great in emacs yet wont paste in a terminal. it always pasts an older entry and not the selected one

thx again

z

**Comment by scottkosty** [comment]
Hi Zeltak, can you please give more details? What do you mean "selecting"? With keyboard pressing return? Left-clicking with the mouse? And what terminal application are you referring to? gnome-terminal? xterm? Does CopyQ work well in other applications (in addition to emacs)? Ignoring copyQ for a second, if you copy something (with ctrl c) and then go to your terminal application and press "shift + insert" does it paste what you copied?

P.S. I agree that CopyQ is an amazin app. Lukas is doing some impressive work.

**Comment by zeltak** [comment]
Hi scottkosty

well the terminal is terminator but all other terminals dont work. the way i tried is both using shift-insert or using the auto insert command built in copy. i launch the menu or the full copyq app choose a clip, press enter and it dosent paste the selected entry. in contrary on emacs or any other editor it does work.

copy and pasting from other apps into the terminal works very well with no issues. also using other clip managers (ie gpasted etc) also works well
im using arch linux with latest copyq from git. ill be very happy to help try and debug this (although im very non technical :))

thx

z

**Comment by scottkosty** [comment]
ah the name of the program is just "terminal" ? If you run the command `xprop WM_CLASS` and then click on the terminal, what does it say there?

That's very useful information that other clip managers work.

It's also useful to know that shift + insert does not work, since I think that's how CopyQ communicates with programs (by sending those keys). I'm not sure though.

**Comment by hluk** [comment]
Yes, CopyQ sends `Shift+Insert` to paste clipboard. That's defacto standard shortcut which works in most apps and even terminal emulators. Perhaps the application has bug or feature request for this.

Note: Supporting other shortcuts to paste would add a lot of complexity to CopyQ. Passing shortcut needs to be implemented on more platforms and handling keyboard modifiers is not trivial. Also there would need to be some table with mapping which shortcut to use in which windows. So I'm not planing to add this.

**Comment by hluk** [comment]
I completely forgot about this, but there is hidden option in CopyQ for pasting with **Ctrl+V** (commit de17a4abd2edf2bd16ca8798b7948b0391231490).

You can edit your `~/.config/copyq/copyq.ini` and add under `[General]` section add the following line.

```
paste_with_ctrl_v_windows="terminal|Terminator"
```

The value is regular expression for matching window titles where CopyQ will send **Ctrl+V** instead of **Shift+Insert**.

Anyway, I just tested the behavior and I can paste with **Shift+Insert** in Terminator terminal emulator (v0.97) and it works from CopyQ.

I'm closing this, reopen if this is still an issue.
