### ISSUE TITLE
CopyQ toggle 

### ISSUE THREAD

**Issue by sac2171** [hluk/CopyQ#339]
While CopyQ show, and CopyQ hide work fine, CopyQ toggle seems to keep the window in thee state it was previously,  (do nothing) rather than toggle. I'd like to either get the toggle functionality working, or ask for a feature request for hide and show to return 1 if already in that state, so a simple shell toggle could look like copyq show || copyq hide

**Comment by hluk** [comment]
Command `toggle` **shows and focuses** main window if it **doesn't have focus**, otherwise the window is hidden or minimized. This should work well if you have multiple desktops but could misbehave with some window managers.

So is the problem that you want to hide the main window if it's visible but doesn't have focus?

**Comment by sac2171** [comment]
Correct.

**Comment by hluk** [comment]
In next version, you should be able to use following command to show/hide main window.

    copyq eval 'visible() ? hide() : show()'
