### ISSUE TITLE
Buttons for change format

### ISSUE THREAD

**Issue by SamHasler** [hluk/CopyQ#346]
To make the change format shortcuts more discoverable¹, could left/right buttons be place at the far right of an item, with appropriate tooltip, when mouse hovering over an item or it has focus from arrow key presses. (So when first opening the window it would appear for item 0 as that is focused.)

The styling of the buttons needn't be overly heavy, just "◀ ▶" in grey without any box around them would do.

Some way of revealing the the number of formats available, and the current format would also be helpful. How about "◀ 1/3 ▶", and on change it shows the format name to the left of that and fades it out.

But please, DON'T add this if it would slow down the appearance of the window or rendering of the items when pressing the Show/hide main window shortcut.

¹ I've been using CopyQ over 4 months and only discovered it had this feature today.

**Comment by hluk** [comment]
One of first versions of CopyQ had horizontal list of display formats at the bottom of each item. I removed it because the information was in most cases useless and it cluttered the history with unnecessary info.

For me changing the display format is useful only when an item contains text, HTML and image. Sometimes the HTML cannot display the image (Web plugin is usually required but it misbehaves sometimes). But in that case I usually see that something is wrong and know that there is probably another format.

Do you need to change the format in some specific cases?

Tip: You can change display format priority by reordering items in "Item" configuration tab.

**Comment by SamHasler** [comment]
Usually it's because I want text instead of HTML.

The biggest issue for me was being able to discover the Ctrl+Left / Ctrl+right shortcuts. Instead of changing the display format, could you add left/right buttons to the toolbar?

**Comment by hluk** [comment]
Done. It should have been in menu/toolbar anyway.
