### ISSUE TITLE
No console output on Windows

### ISSUE THREAD

**Issue by hluk** [hluk/CopyQ#349]
Console executable `copyq.com` build with Qt 5 is unable to print anything on console.

~~Console output works with Qt 4 but when tests processes are started as `QProcess` then there doesn't seem to be anything printed to stdout or stderr.~~

~~If this is fixed and tests work as expected, test can be run using [AppVeyor](https://ci.appveyor.com/project/hluk/copyq) (#347).~~

**Edit:** The console app in Qt 4 seems to work fine (problem was release version didn't print debug info needed for passing keys in tests - fixed in commit e82f162186cb3561708ea5ba7eef380e4729ad25).

**Edit 2:** Tests run on AppVeyor but the whole process takes too much time and is killed before it can finish. Console output is still unavailable with Qt 5 (tested with `cmd` and `git-bash`).

**Comment by hluk** [comment]
I have no idea why this is not working. If anyone can fix this that would be really great.

**Comment by hluk** [comment]
This should be already fixed.

**Comment by pbodnar** [comment]
Hi, **this doesn't seem to be fixed** on Windows 10. I tried with the latest versions of CopyQ (3.10.0, 3.11.1) and copyq doesn't output anything from both plain command line or PowerShell.

Luckily all the possible **workarounds** described at the [comment](https://github.com/hluk/CopyQ/issues/499#issuecomment-215710347) for #499 seem to work. But I think this issue should be also visibly mentioned on the [documentation page](https://copyq.readthedocs.io/en/latest/command-line.html), unless the issue gets fixed, of course...

**Comment by pbodnar** [comment]
**Regarding how to fix this issue**, on the internet they offer about two solutions for hybrid (gui + command line) applications like CopyQ:

1) According to [this](https://stackoverflow.com/questions/3886105/how-to-print-to-console-when-using-qt), it is possible to use a special wrapper around the `stdout` stream called `QTextStream`. But it looks like one needs to output everything to that wrapper instance instead of to `cout`. I find this solution kinda strange...

2) According to [this](https://stackoverflow.com/questions/3360548/console-output-in-a-qt-gui-app), it is possible to call `AttachConsole(ATTACH_PARENT_PROCESS)` ([MS docs](https://docs.microsoft.com/en-us/windows/console/attachconsole)) and then to call something like `freopen("CONOUT$", "w", stdout)`, which causes redirection of `stdout` to the attached console. There is also possibly an important note on pipe-ing functionality:

> ... you can use GetFileType to determine if a pipe is active. In my modified code, I set stdout_type = GetFileType(GetStdHandle(STD_OUTPUT_HANDLE)); Then, I wrap the freopen for stdout with the conditional: if(stdout_type == FILE_TYPE_UNKNOWN) This seems to effectively allow the process to output to an existing pipe if available, but to the parent console when pipe is not open. – dvntehn00bz Jun 16 '17 at 19:51

As none of this seems to be used in the CopyQ's code right now, there is maybe a chance of that it could work when used? What do you think?

Note that I can't currently try it myself, mainly because I'm rather interpreted languages programmer... ;)

**Comment by hluk** [comment]
I've already spent too much time trying to figure out the right solution. Also, I don't have Windows development environment available and don't see much reason to have this fixed there - not many people complained about the issue.

IIRC workaround was to use something like `copyq clipboard | cat`.

**Comment by pbodnar** [comment]
Hi, regarding workarounds and documentation, see #1433 (at least I've learnt dealing with basics of RST, it was probably inevitable :)).

Regarding fixing it, I see your point, it probably isn't worth trying now. But maybe if some crazy man (not necessarily me ;)) will decide to do so, it would be good for him to have some starting points...

**Comment by Gitoffthelawn** [comment]
For those needing help with this, a workaround for this issue on Windows is to pipe the output to the native `more` command.

For example:

```
copyq help | more
```

**Comment by gabbymouth** [comment]
> For those needing help with this, a workaround for this issue on Windows is to pipe the output to the native `more` command.
> 
> For example:
> 
> ```
> copyq help | more
> ```

Or copyq help | find /v ""  or copyq help | findstr "^"

**Comment by Chealer** [comment]
Thank you for reporting Lukas and thank you for the workaround @Gitoffthelawn 
This persists in 13.0.0. Ticket #2937 offers another workaround.

<details>
  <summary>License</summary>
This comment and any other from myself on this ticket is offered under the terms of CC0 1.0.
</details>

**Comment by Chealer** [comment]
This persists in 14. Please retitle to something more precise, like:
> ``copyq`` console command prints nothing in Windows Terminal, Windows Console and Tabby

The following rectifies the known issue section and adds the other workaround:
```diff
diff --git a/docs/known-issues.rst b/docs/known-issues.rst
--- docs/known-issues.rst
+++ docs/known-issues.rst
@@ -19,24 +19,24 @@
     `Issue #1258 <https://github.com/hluk/CopyQ/issues/1258>`__
 
 .. _known-issue-windows-console-output:
 
-On Windows, CopyQ does not print anything on console
+On Windows, ``copyq`` console command prints nothing
 ----------------------------------------------------
 
-On Windows, you may not see any output when executing CopyQ in a
-console/terminal application (PowerShell or cmd).
+On Windows, you may not see any output when executing CopyQ in Windows Terminal, Windows Console, Tabby and possibly other terminal emulators.
 
 **Workarounds:**
 
-* Use different console application: Git Bash, Cygwin or similar.
-* Use Action dialog in CopyQ (``F5`` shortcut) and set "Store standard output"
-  to "text/plain" to save the output as new item in current tab.
+* Use mintty (shipped by Cygwin and Git Bash)
 * Append ``| Write-Output`` to commands in PowerShell:
 
   .. code-block:: powershell
 
     & 'C:\Program Files\CopyQ\copyq.exe' help | Write-Output
+* Append ``| cat`` to commands in Bash
+* Use Action dialog in CopyQ (``F5`` shortcut) and set "Store standard output"
+  to "text/plain" to save the output as new item in current tab.
 
 .. seealso::
 
     `Issue #349 <https://github.com/hluk/CopyQ/issues/349>`__

```

**Comment by pbodnar** [comment]
@Chealer, thank you for trying to make the documentation more clear. But as explained elsewhere recently, can you please create a pull request for this, so that the suggested changes can be easily seen & discussed? Or at least mark your inline patches as `diff` (after those [opening tripple backticks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting)). Thank you.

**Comment by Chealer** [comment]
@pbodnar: Assuming we're talking about a "merge request", I don't have a particular CopyQ branch. But I specified the highlighting type above, thanks for reminding(?) me.
