### ISSUE TITLE
Set configuration location via command line

### ISSUE THREAD

**Issue by majkinetor** [hluk/CopyQ#359]
On Windows, my copyq is installed in Program Files. Configs are kept in its dir. Is it possible to move those to $HOME directory, or to check there first then fullback to app dir (or at least provide command line option to specify config dir).

If this is already implemented I wasn't able to find it.

**Comment by majkinetor** [comment]
WIth UAC enabled this also requires elevated rights to save to configuration.

**Comment by hluk** [comment]
This is fixed in 64706ce06fce54f58dc12d2e4c19d61fd1e99da9 - see [documentation](https://copyq.readthedocs.io/en/latest/sessions.html#configuration-path).

It's not yet released (not in 3.5.0) but you can grab [build with the feature](https://ci.appveyor.com/project/hluk/copyq/build/1.2.1733/job/h04f36copb04qlut/artifacts).
