### ISSUE TITLE
Keep custom-created tabs and commands synced?

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#366]
Hi all, 

I would like to keep my custom-created tabs and commands synced automatically with my Dropbox. Thus I want to symlink them from their default location to my Dropbox folder. 

Could you please tell me where CopyQ stores those tabs and custom commands?

Is it sufficient to symlink the entire folder `~/.config/copyq`?

Thankfully, 

Robert

**Comment by scottkosty** [comment]
Hi orschiro,

Please only post bugs or enhancement requests here. If you want to ask a question, please ask on the google group:
https://groups.google.com/forum/#!forum/copyq
That said, my guess is that symlinking the entire folder is "sufficient" but I think you will pick up temporary files that are changing frequently and thus causing frequent syncs with dropbox. I would just suggest that you experiment. For example I see copyq_tabs.ini in that folder. I don't know what it does since I don't currently use tabs, but it might be something you want to sync.

If you have any further questions, please ask them on the google group.

**Comment by orschiro** [comment]
@scottkosty 

Thanks, will do so in the future!

For reference: Backing `copyq_tabs.ini` worked.

**Comment by scottkosty** [comment]
Great, thanks for letting us know it worked!
