### ISSUE TITLE
Notify about duplicate commands in Command dialog

### ISSUE THREAD

**Issue by rachmadaniHaryono** [hluk/CopyQ#370]

**Comment by hluk** [comment]
This is very unhelpful. I don't know what "duplicate commands" refer to.

**Comment by scottkosty** [comment]
I agree that the description is not helpful. rachmadaniHaryono, whenever making a bug report or feature request, please give an example. Also please say *why* such a feature is useful (give a real user case that is believable).

At first I thought the OP wanted a command that would remove duplicate items from the clipboard. However, if I copy something that is already in the clipboard, isn't it just moved to the top or is this a preference that I have set?

**Comment by hluk** [comment]
Duplicate items could still appear in clipboard tab.

Copied Item is moved to top only if it matches completely (all data types that are stored are the same -- only hash of items are compared so this is fast). Otherwise the top item can be updated if the new text is same or just contains the item text -- this is useful when user is just extending previously selected text and copies again.

There is a small bug with the latter -- I have fixed that but it isn't committed yet.

**Comment by rachmadaniHaryono** [comment]
I'm sorry. Got Internet connection problem. 

I want to request a feature to remove duplicate command. I accidentally copy and paste the commands in command list so I got my command doubled and there is no easy way to remove the command. So maybe 
* a way for sorting command by creation date
* a warning if a duplicate command is added
* an addition to filename if duplicate found 

Out maybe there is an easy way that I overlook. 
Thank you

**Comment by rachmadaniHaryono** [comment]
@hluk, i will close this issue because i think this my PBCK.

i am not quite sure if there is anyone need this feature after years, but this issue can be reopened if there is any
