### ISSUE TITLE
Problem installing/running dmg file on OS X

### ISSUE THREAD

**Issue by reagle** [hluk/CopyQ#389]
I've set my security to open non-app-store and non-approved devs; I've downloaded "CopyQ-2.4.9.dmg", I click it, see a folder with CopyQ and Applications; I click CopyQ and nothing happens. Nothing appears in the menu or status bars.

**Comment by reagle** [comment]
Looking around, I'm not sure I've seen any recent evidence that the osx builds actually work...?

**Comment by hluk** [comment]
I cannot test CopyQ on OS X.

@rygwdn, any ideas what can be wrong?

**Comment by hluk** [comment]
Actually, there is also #386 which can be related to this.

**Comment by reagle** [comment]
I'm happy to test, but is there an earlier version which is known to work?

**Comment by nirmalksamuel** [comment]
Agree with this bug. Few hours back I downloaded "CopyQ-2.4.9.dmg" onto my new installation of OS X 10.9.x (i don't think OS version matters here)...., I click it, see a message box popup with CopyQ and Applications; Moved CopyQ to Applications by dragging it. Installation went fine because i see a "copying...."  popup and it takes a few seconds to copy/uncompress/install (my guess here).  Then, i see the icon in my Applications folder.  Navigating to that folder, or searching through LauchPad, i see the CopyQ icon, but clicking on it does not work.  nothing happens. Nothing appears in the menu or status bars.   This is NOT a permissions problem, because when i clicked first time i got a warning about CopyQ not being an Apple authorized application and security warning.  After fixing that,  i am able to get over that warning,  but application does not launch.  Wanted to give a detailed report, so that you can work on it.

**Comment by reagle** [comment]
Thanks for the confirmation! I use CopyQ on Linux, and was hoping I could use it in other environments too.

**Comment by hluk** [comment]
I'm closing this as duplicate of #386. If you don't think it's the same issue, please provide more info (error messages from command line?).

**Comment by reagle** [comment]
I'm not sure if mine is even installed. It doesn't show up on applications and trying to emulate #386 gets me nowhere.

```
ird:~$ otool -L /Applications/CopyQ.app/Contents/Frameworks/QtSvg.framework/QtSvg 
error: otool: can't open file: /Applications/CopyQ.app/Contents/Frameworks/QtSvg.framework/QtSvg (No such file or directory)
```

**Comment by reagle** [comment]
I followed @nirmalksamuel's steps and dragged the icon to the Applications folder. It appears to be installed. Now when I run the command I get:

```
ird:~$ otool -L /Applications/CopyQ.app/Contents/Frameworks/QtSvg.framework/QtSvg
/Applications/CopyQ.app/Contents/Frameworks/QtSvg.framework/QtSvg:
        @executable_path/../Frameworks/QtSvg.framework/Versions/5/QtSvg (compatibility version 5.5.0, current version 5.5.0)
        /usr/local/Cellar/qt5/5.5.0/lib/QtWidgets.framework/QtWidgets (compatibility version 5.5.0, current version 5.5.0)
        /usr/local/Cellar/qt5/5.5.0/lib/QtGui.framework/QtGui (compatibility version 5.5.0, current version 5.5.0)
        /usr/local/Cellar/qt5/5.5.0/lib/QtCore.framework/QtCore (compatibility version 5.5.0, current version 5.5.0)
        /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
        /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
        /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
        /System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

**Comment by hluk** [comment]
Yes, that's bad. The Qt libraries should be bundled with the application. If the app will try to use different libraries it will probably crash (that's what happens now).

**Comment by nirmalksamuel** [comment]
This  issue  got closed by mistake i think.  This is still present - i tested versions 2.4.9 as well as 2.4.8. Both have same trouble in  OS X 10.9.5.  Please reopen this,  for me to add further comments during testing.  I am willing to test (don't know how i can get notified via email about changes to these discussions. Will look into Github options).
-------------
Thanks for the comment.  Downloaded 2.4.8 for OS X for fresh copy just now.  Rebooted my machine to be sure. Installed 2.4.8.  This has same problem i described elsewhere - does not open, nothing is shown  in macbook Dock or at top.  Tried to start it from Terminal using command line CopyQ. It can not find the application anywhere.  Is there any version of this that has been tested to work on OS X ? 
------------------

**Comment by nirmalksamuel** [comment]
oops sorry - in a hurry - font got messed up.

**Comment by hluk** [comment]
Can you test with newly uploaded [package for OS X](https://github.com/hluk/CopyQ/releases/tag/v2.4.9)? (See also [this disscusion](https://github.com/hluk/CopyQ/issues/386#issuecomment-149030169).)

**Comment by reagle** [comment]
I can now install and run, thanks!

**Comment by nirmalksamuel** [comment]
I downloaded from the  2.4.9 release link given by hluk.  It is showing the icon as well as opens now. I am new to copyQ, so can not test functionality, but initial look at preferences shows i will come to like this software.  Now....if only i can find a documentation to quickly introduce me to various aspects of this, i will be able to navigate the preferences faster.  Quick google search does not yield anything for documentation.  I am sure there is one lurking around.  Can you point me to it ? Thanks to the entire dev team of this work.

**Comment by hluk** [comment]
Documentation is here: https://github.com/hluk/CopyQ/wiki

The app is meant to be used without documentation (for normal use) and user should be able to discover features easily. But most of the stuff is based on what I consider user-friendly and there are still some weird places so let me know if you have any ideas how to make the app easier to learn and less confusing.

**Comment by nirmalksamuel** [comment]
Thanks  hulk.  As i begin to use this as new user, i will discover things that are seen from a new user perspective.  I will add the notes here in this thread for you to see, as i come across them. For starters, what got me on checking for docs (which i don't use for small apps usually) is that i saw some of the items in the history list are shown as <FILES> (when i click on icon).  But when i open up, i see that they are just  youtube links.  Some other youtube links are showing up fine.  Could it be because i used Control-x  ??  That's my guess, but i need to check with doc, because i don't really remember what i did days before.  It would be useful  to put something more descriptive than <FILES> in that list.

**Comment by hluk** [comment]
@nirmalksamuel Please create new issues instead of adding comments to this unrelated one.
