### ISSUE TITLE
Can't create global command to toggle clipboard storing

### ISSUE THREAD

**Issue by SamHasler** [hluk/CopyQ#394]
I'd like to reimplement Enabling/Disabling clipboard storage (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>X</kbd>) as a global command:

```
copyq: 
if (/* What goes here? */) {
  enable();
} else {
  disable();
}
```

**Comment by SamHasler** [comment]
Aside: it might be less confusing if there was only one place where commands/shortcuts were configured and you could tick a checkbox to say if they were global or only when the CopyQ window was open.

**Comment by hluk** [comment]
Call `monitoring()` returns true iff clipboard is monitored/stored. So the whole command is:
```js
copyq:
if (monitoring())
  disable()
else
  enable()
```

You can configure global and menu shortcuts separately (different shortcut for both) and menu shortcut can be only set if the command is in menu (otherwise I think it would be a bad practice). I'll try to change it in #396 (please comment there if you have any ideas).
