### ISSUE TITLE
Multiple instances on different X displays

### ISSUE THREAD

**Issue by blueyed** [hluk/CopyQ#416]
I want to use CopyQ simultaneously on different X DISPLAYs, but when starting it for the 2nd time it bails out:

> CopyQ warning: CopyQ server is already running.

btw: while it says "warning" this should be an error instead, and the exitcode should be non-zero.

I could imagine to just use `DISPLAY` in the servername (https:…/common/client_server.cpp#L39), and/or to be able to pass your own servername.

With two servers running simultaneously, it would be great if their data could be either merged or kept separate; I can see a use case where you would want to keep the history separate, but for me it would be OK and useful to have it mixed.

My use case is using another X server instance (DISPLAY) for work and private stuff.

I see these processes currently:
```
user    1217  0.0  0.4 2616128 71736 tty1    Sl   12:02   0:06 copyq
user    1312  0.0  0.2 387688 34384 ?        Sl   12:02   0:01 /usr/bin/copyq monitor /home/user/.config/copyq/.copyq_m…
```

**Comment by hluk** [comment]
The idea behind the zero exit code is that since the application is already running there is nothing to do. Changing it will break some scripts and I don't want to do that.

There cannot be two running instances of the application because both would want to write and read the configuration and data. That would require using a system mutex or another server that handles writing/reading exclusively.

You can still run separate instances of the application giving them unique session names. So you can run both `copyq` and `copyq -s my_second_instance` simultaneously. Though each session has its own configuration and items.

Not sure if anyone is using that feature, but I think it can be quite handy and I would love to get some input from users.

**Comment by blueyed** [comment]
Thanks!
The session feature is what I was looking for.

I've also seen that you can set it in the environment (`COPYQ_SESSION_NAME`), although that seems to be undocumented?!

I am closing this issue for now.

**Comment by hluk** [comment]
The environment variable is used for setting session automatically so that you can simply use `copyq` without extra arguments in commands. So it wasn't meant to be used explicitly by user though there shouldn't be any problem. Anyway, nice find!

**Comment by blueyed** [comment]
> it wasn't meant to be used explicitly by user though there shouldn't be any problem

In a multi-display environment it's somehow required though, if you want to use `copyq` as-is in both of them - without a wrapper script.
