### ISSUE TITLE
Can't Run CopyQ In Linux 

### ISSUE THREAD

**Issue by lowboy** [hluk/CopyQ#430]
1.  Environment: Archlinux-Manjaro x86_64 version 228
2. I tried to install CopyQ in many ways cluding with ***`pacman`***, with ***`yaourt`*** and ***compiling with source code***, neither ways  works out for me.
3. While installing CopyQ, none error is shown, however, CopyQ can't be correctly started by clicking its icon.
4. When I type ***`copyq`*** in terminal, it returns ***```CopyQ warning: CopyQ server is already running.```***, which indicates that copyq is already autostarted at system' startup;
while when I run ***`copyq toggle`***, it returns ***```CopyQ ERROR: Cannot connect to server! Start CopyQ server first.```***

Thanks~

**Comment by scottkosty** [comment]
OK let's focus on getting it working after you compile with source. This will be the easiest so that you can test a fix if we are able to come up with one.

First, remove all CopyQ installations. Then, clone the latest git. Then compile. Can you please post your CMakeCache.txt file?

Assuming the compilation and installation went well, please run the following commands:

    export COPYQ_LOG_LEVEL='DEBUG'
    export COPYQ_LOG_FILE='copyq.log'
    copyq

Can you then paste the contents of the copyq.log file (it should be in the same directory where you ran the copyq command).

**Comment by scottkosty** [comment]
@lowboy any update?

**Comment by scottkosty** [comment]
@lowboy please try with 2.7.1 and if you have the same problem reopen with more details after taking a look at my first comment.

**Comment by tubersan** [comment]
CopyQ won't start for me either unless I run it as root or with sudo

```
$ COPYQ_LOG_LEVEL='DEBUG' COPYQ_LOG_FILE='copyq.log' copyq

(copyq:16992): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(copyq:16992): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(copyq:16992): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(copyq:16992): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(copyq:16992): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
Gtk-Message: Failed to load module "canberra-gtk-module"
CopyQ Warning [2016-08-02 14:31:10.595]: CopyQ server is already running.

$ cat copyq.log
CopyQ DEBUG [2016-08-02 14:31:10.595]: Opened session mutex: copyq_mutex
CopyQ DEBUG [2016-08-02 14:31:10.595]: Server "/home/alex/.config/copyq/.copyq_s" already running!
CopyQ Warning [2016-08-02 14:31:10.595]: CopyQ server is already running.

$ cat /home/alex/.config/copyq/.copyq_s
cat: /home/alex/.config/copyq/.copyq_s: No such file or directory

$ ls /home/alex/.config/copyq/
copyq-bak.conf  copyq.conf  copyq-filter.ini  copyq_geometry.ini  copyq.pub  copyq_tab_JmNsaXBib2FyZA==.dat  copyq_tabs.ini  themes
```

**Comment by hluk** [comment]
Please post output of following command.

```bash
ls -la /home/alex/.config/copyq/
```

**Comment by tubersan** [comment]
```
total 4216
drwxr-xr-x  3 alex alex    4096 Aug  3 15:34 .
drwxr-xr-x 31 alex alex    4096 Aug  5 23:31 ..
-rw-r--r--  1 alex alex    4975 Aug  3 15:57 copyq-bak.conf
-rw-r--r--  1 alex alex    4975 Aug  3 15:57 copyq.conf
-rw-r--r--  1 alex alex      36 Aug  3 15:57 copyq-filter.ini
-rw-r--r--  1 alex alex    2787 Aug  3 15:57 copyq_geometry.ini
-rw-------  1 alex alex       0 Aug  3 15:57 copyq.pub
-rw-r--r--  1 alex alex 4275745 Aug  3 15:57 copyq_tab_JmNsaXBib2FyZA==.dat
-rw-r--r--  1 alex alex     153 Aug  3 15:57 copyq_tabs.ini
drwxr-xr-x  2 alex alex    4096 Aug  3 15:34 themes
```

`copyq show` and `copyq tab` only give the same `CopyQ ERROR: Cannot connect to server! Start CopyQ server first.` error as @lowboy already mentioned.

**Comment by tubersan** [comment]
Mmh well, I had previously removed copyq again since it was not working (I didn't remove the config folder though).
I just installed it again to check the specific error it threw, but now it's working perfectly fine.
I guess I had an old version running before without noticing.
Either way I'm sorry for the trouble, but I think this issue can be closed again.

**Comment by hluk** [comment]
OK, no problem. I'll try to add more error/warning messages anyway.
