### ISSUE TITLE
Run in background without tray icon

### ISSUE THREAD

**Issue by forteller** [hluk/CopyQ#434]
First: Love the program, it's a real life saver!

So: I'd like to run it without tray icon, because I use Gnome Shell, and Copy Q is often the only thing I have in the tray down in the lower left corner. But when I choose to "Disable tray" in the preferences the main window of Copy Q stays open. When I try to close it it just minimizes.

I have my keyboard shortcut to open the Copy Q window, that's all I need. Please let me run it in the background without the tray.

Thanks!

**Comment by hluk** [comment]
I don't like the idea of having a GUI application running on system without being visible at all.

Is this really a problem? I thought that minimized windows are visible as simple non-intrusive icons in side panel in Gnome Shell (if you don't use another extension).

**Comment by guraga** [comment]
I want this too. Please, add option to hide CopyQ's window from alt-tab dialog and from task bar. This just like terminal emulator -- when you need it you press keyboard shortcut.

I'm trying to use openbox's window rules:
```xml
<application
name="copyq"
class="Copyq"
type="normal"
>
<skip_taskbar>yes</skip_taskbar>
<skip_pager>yes</skip_pager>
</application>
```
but this does not work. Please, do not ignore window manager rules.

Do you know some ways to hide CopyQ's minimized window?

**Comment by forteller** [comment]
I guess you're right. That could create a lot of trouble, if you haven't set or don't remember the keyboard shortcut. Ok, just forget about it :)

**Comment by hluk** [comment]
@guraga CopyQ doesn't ignore window manager rules. It tries to do as little as possible so that main window behaves correctly. I spent too much time writing lot of code to work around behaviors of some WMs and it still doesn't work well everywhere.

I've tried to remove and simplify some of the code in [simple_window_management](https://github.com/hluk/CopyQ/tree/simple_window_management) branch. I tested it only briefly so if anyone can **please test it**.

**Comment by hluk** [comment]
Update for the window management: I just tested the new branch and various other fixes on Ubuntu and it doesn't behave well -- so I'm not changing the behavior now.
