### ISSUE TITLE
CopyQ toggle

### ISSUE THREAD

**Issue by aksr** [hluk/CopyQ#448]
If tray is disabled, `copyq toggle` doesn't work (doesn't hide the main window).
In other words, CopyQ main window is always shown if the tray is disabled.

Latest git version:
CopyQ Clipboard Manager v2.6.1-1-ged3d962
Built with: Qt 5.5.1, LibQxt 0.7.0

**Comment by hluk** [comment]
I cannot reproduce this issue on Windows and Linux. What is your OS or window manager?

It's possible that when you run `copyq toggle` the window momentarily loses focus which means that the command needs to refocus the window. You can try following command instead.

    copyq eval 'if (visible()) hide(); else show()'

**Comment by hluk** [comment]
Actually, I'm looking at the code and losing focus for momentarily shouldn't matter -- that case is handled.

**Comment by aksr** [comment]
Arch Linux, i3

You're right, it does lose a focus for a bit, but it doesn't hide the main window.
(If it does hide it, it's hidden for <1second, then it reappears. (I'm not sure.))
I tried both: `copyq toggle` and `copyq eval 'if (visible()) hide(); else show()'`

**Comment by hluk** [comment]
Qt doesn't provide full control over the X11 window and the app needs some hacks (for example to open window on current desktop). I simplified the window management code in recent versions of the application (tested on Openbox, Windows and Ubuntu). Unfortunately there is still plethora of window managers that can break the behavior.

I'm not sure how to handle this properly. If I fix issues on on manager, something can break on another and there no simple way to test this.

Since i3 is so successful, I'll try to use it instead of Openbox.

**Comment by hluk** [comment]
There is now option to hide window when closed -- option "Hide main window" under "Layout" config tab.
