### ISSUE TITLE
Support for Android platform

### ISSUE THREAD

**Issue by hluk** [hluk/CopyQ#449]
Some fixes are in [android](https://github.com/hluk/CopyQ/tree/android) branch.

**Comment by hluk** [comment]
Dropping.

**Comment by RichardBoettcher** [comment]
Any plans for this to be picked back up?

**Comment by hluk** [comment]
I don't see many reasons for this app to support Android -- I don't use clipboard extensively on mobile devices.

Supporting Android would require many UI changes and implementing some feature only needed for mobile devices.

If someone else want to give it a shot, the "android" branch might be a good start. I remember that I managed to start CopyQ on my phone but without much functionality and the code have changed a lot since then.

**Comment by NA0341** [comment]
@RichardBoettcher There's already a really good solution to this:

⮱ Install a good Clipboard Manager¹ on you Phone which is built to run on an Android Device.
⮱ Use KDE - Connect to automatically sync Everything you copy between your Phone(s) & Desktop(s).

Why? Because it's probably the best way to do it.

KDE - Connect syncs Everything you configured it to in Real Time as soon as the two devices can communicate over a network. It uses industry standard TLS encryption (256bit AES) and has so many features that I would say: It connects your devices far better than a mouse & keyboard connect you & your computer!
You can even directly send keyboard input to your device via KDE - Connect's remote Keyboard!

Hope this helps :)

~ NA0341

¹ I currently use XClipper from F-Droid. It's okay but beware it does **not** behave how you'd expect! Swiping right deletes Every Item (also pinned ones - seems the dev didn't fully get what "pinning" an item means) - even when this feature is "disabled" in setting :facepalm:

**Comment by Kmfernan5** [comment]
How can I connect XClipper to Copyq? There must be a way since they both sync via Google Drive right? @NA0341

**Comment by gerardbosch** [comment]
> @RichardBoettcher There's already a really good solution to this:
> [...]
> KDE - Connect syncs Everything you configured it to in Real Time as soon as the two devices can communicate over a network. It uses industry standard TLS encryption (256bit AES) and has so many features that I would say: It connects your devices far better than a mouse & keyboard connect you & your computer! You can even directly send keyboard input to your device via KDE - Connect's remote Keyboard!

👏👏 Thanks to let me know this! With "KDE Connect" I'm now able to transfer clipboard to my phone on demand, and vice versa! Very useful!!

I'm using KDE Connect on the phone side and GSConnect on the computer side, as it provides better integration with Gnome —though it has some broken features at this moment, but can be workarounded: https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1215#issuecomment-1701696864

There's also an option for 2-way sync of clipboard between phone and computer, but I prefer to do it on demand.

_Note: This only works when both devices are connected to the same network and you may need to open ports in your local computer firewall._

**Comment by NA0341** [comment]
> @Kmfernan5 How can I connect XClipper to Copyq?

The clipboard manager is meant as a measure to not loose content while not connected to desktop.
It also provides simple means of clipboard management on mobile without relying on desktop software.

Maybe I phrased that in a misleading way :thinking:

---

@gerardbosch Thanks for the link to the workaround (=

About the firewall thing: This should only apply to Windows. I'm 100% a GNU/Linux user since April 2016 who did do a lot of different things - and I never even had to think about a firewall - because it does not get in my way.

BTW: Since I know lots and loads of software, tools and ways to do things, I want to share all this knowledge with the world.
The big challenge here is putting it all together in a way that others can benefit from it.
I'll be putting several services on my own server - and am planning to put a knowledge base with all the mentioned experience as well. But this might take some time.

So for reference I'll put my Link Navigation Page here where my website can be found at some point: https://bio.link/na0341
