### ISSUE TITLE
Tray-Icon: Scissors symbol should stay closed when clipboard monitoring is disabled

### ISSUE THREAD

**Issue by pre55** [hluk/CopyQ#457]
##### When clipboard monitoring is disabled:
![Closed scissors](http://abload.de/img/copyq261_improvement_vis62.png)

##### When clipboard monitoring is enabled:
![Opened scissors](http://abload.de/img/copyq261_improvement_pvsy9.png)

**Comment by hluk** [comment]
What's the reasoning behind this? I guess it's hard to see the clipboard monitoring state since currently only the color changes slightly.

"Closed scissors" are used to denote that an action/command is running in background (useful to see if something takes too long).

Perhaps I could add a small emblem to the icon when monitoring is disabled.

**Comment by pre55** [comment]
> I guess it's hard to see the clipboard monitoring state since currently only the color changes slightly.

Yes, you are right, that's the reason behind.

Maybe you could solve the denotation issue of the action command by coloring the (two rings of the) scissors red?

Imho it could be very useful to use the opened or closed scissors for best recognization if monitoring is on or off. Recognizing this *main feature* of CopyQ should have priority, shouldn't it?

**Comment by hluk** [comment]
The icon color is generated from session name (e.g. starting "test1" session with `copyq -s test1` creates new app instance with blue icon color).

On the second thought, just closing the scissors (without changing color) when monitoring is disabled is probably the best solution (no new icons and it doesn't mess with the session coloring).
