### ISSUE TITLE
Overwrite items with same prefix

### ISSUE THREAD

**Issue by guraga** [hluk/CopyQ#460]
When
1. select text "a" and press Control+C,
2. then select text "ab" and press Control+C,
3. then select text "abc" and press Control+C,
actual result is following:

```bash

copyq read 0 # will     print "abc"
copyq read 1 # will not print "ab"
copyq read 2 # will not print "a"

```

What happened?
1. Added item "a".
2. Item "ab" overwrite item "a".
3. Item "abc" overwrite item "ab".

Expected result is following:

```bash

copyq read 0 # will print "abc"
copyq read 1 # will print "ab"
copyq read 2 # will print "a"

```

When run commands

```bash

echo -n a   | copyq write "text/plain" -
echo -n ab  | copyq write "text/plain" -
echo -n abc | copyq write "text/plain" -

```
actual and expected results are the same.

**Comment by m4r71n** [comment]
Confirmed on Windows 10. Thx @guraga for reporting.
Every now and then I had the feeling that copied items were missing. That would explain it.

**Comment by hluk** [comment]
It's feature. I implemented this mainly because selecting text on Linux/X11 sometimes caused many similar items to be stored in CopyQ.

Relevant code is [here](https://github.com/hluk/CopyQ/blob/c748384c4fbf5dc5832c2d289a7a49f03a37df84/src/gui/clipboardbrowser.cpp#L1598).

I can ignore this feature for text from clipboard since it's confusing.

**Comment by m4r71n** [comment]
:+1:
