### ISSUE TITLE
CopyQ window jumping up a bit every time invoked

### ISSUE THREAD

**Issue by raqua** [hluk/CopyQ#467]
Hi, 

I am using Cinnamon on Arch Linux, so I should have newer packages than others. Except for issue: https://github.com/hluk/CopyQ/issues/431, which I am also affected by, I am having additional problem. 
Every time I invoke the main window, it's position is a bit higher on the screen. It is jumping up with each invocation, until it reaches top of the screen. 
When I re-position it in the middle of screen, where I would like it to stay (it worked before), next time it starts there, but it will start to travel up again.  

Thanks.

**Comment by hluk** [comment]
Recently I removed some [window management hacks](https://github.com/hluk/CopyQ/commit/46dccfc3803fb0ef10b84496b1c0d42d) from code. So hopefully this will be fixed in next version for most window managers.

If it's not fixed then you may have same issues with your window manager as in #362 where WM moves the window after adding border.

If you use shortcut to show window you can use following (instead of default "Show/hide main window" command).

```ini
[Command]
Name=Show/hide main window
Command="
    copyq:
    if (focused())
      hide()
    else
      showAt(1200, 350)"
Icon=\xf022
GlobalShortcut=ctrl+shift+1
```

(Copy/paste the above to command list in Command dialog <kbd>F6</kbd> and change the shortcut and the position on screen `1200, 350`.)
