### ISSUE TITLE
Synchronize items with files (documentation?)

### ISSUE THREAD

**Issue by bigalgeorge** [hluk/CopyQ#473]
Hi Im sure I had the Synchronize to folder working properly some time back, but now I want to use the function so that my Android with dropbox can access Copyq history.
Wiki says nothing about Synchronize can you please advise how to set it up so it works?
If I set up a directory under Synchronize there is nothing written to it.

**Comment by hluk** [comment]
You just need to set "Tab Name" and "Path" columns in the table and then create the tab with exactly the same tab name. Some files won't be visible because the file suffix is not recognized (MIME type can be assigned to file suffix in the second table in Synchronize settings).

Can you provide more info if this still doesn't work?

**Comment by bigalgeorge** [comment]
Ah, found it was non-exact naming I had used 'clipboard' in the sync whereas it was &clipboard.
Thank you   :-)
Only problem stops me from using it I kept getting text clipboard item then <DATA>
THUS:
here is the text item
<DATA>

Thank you, Alistair

**Comment by bigalgeorge** [comment]
Sorry that did not read right due to github formatting here is something like:
here is the text item
.<DATA.>
