### ISSUE TITLE
If disable_tray=true I am unable to close copyq window

### ISSUE THREAD

**Issue by DoTheEvo** [hluk/CopyQ#474]
arch + i3wm
copyq v2.6.1

as title says, if I go in to `~/.config/copyq/copyq.conf` and set `disable_tray=true` I lose the ability to close the window of copyq and by close I mean hide it, minimize it...  since it does not really quit on close command

arch + xfce
copyq v2.6.1
Tested this in virtual machine with xfce as well, and there it works in sense that the window disappears, but in taskbar theres still active copyq instance leftover

**Comment by scottkosty** [comment]
after you set that preference, what happens when you click on the x in the main CopyQ window?

Note that this works fine for me on Ubuntu (with the default unity).

Also, are you using copyQ with Qt4 or Qt5?

**Comment by DoTheEvo** [comment]
* in i3 theres no [x] to close, just keyboard shortcut or a mouse gesture, and those do nothing at all
* in xfce tested in virtual machine.. theres that leftover [taskbar instance](https://d2.maxfile.ro/avmeatwbmm.webm)

I believe Qt5 is used

**Comment by hluk** [comment]
If you disable tray closing the window will cause it to be minimized by default instead of hidden. Some window managers (mainly tiling WMs) don't support minimizing so the window will stay open. 

Recently I've added option to always hide the window when closed ([commit](https://github.com/hluk/CopyQ/commit/798cec13810a8027ee04f841ce66e8514886aa9e)).

I still think the option can be dangerous because you won't see that the application is running and you have no way to show the main window other than using global shortcuts or command line.

Note: If you want to quit the application use <kbd>Ctrl</kbd>+<kbd>Q</kbd> shortcut or `copy exit` command.

**Comment by DoTheEvo** [comment]
well, it worked fine previous versions

**Comment by hluk** [comment]
It worked because CopyQ tried to detect if WM supports minimizing windows. It was ugly code and in most cases unnecessary so I removed it (it's now replaced with the new option).

**Comment by smahm006** [comment]
For i3 users set `hide_main_window=true` in ~/.config/copyq/copyq.conf
