### ISSUE TITLE
Unsatisfiable dependency on Ubuntu 16.04

### ISSUE THREAD

**Issue by GrouchyGaijin** [hluk/CopyQ#493]
I just did a fresh install of Ubuntu 16.04 and if I try to install any of the deb packages for CopyQ I get this message: Error dependency is not satisfiable libqt4-gui

**Comment by chamilad** [comment]
Coming across the same issue. It seems 16.04 doesn't have a package named `libqt4-gui`.

http://packages.ubuntu.com/search?keywords=libqt4-gui

**Comment by hegart-dmishiv** [comment]
I've experienced the same here. I'm running Lubuntu 16.04 (Xenial Xerus) and tried installing the CopyQ package for Ubuntu 15.10.

**Comment by hluk** [comment]
See #488 and #463.

The package still fails to build on OBS. If you can help with that see the [log](https://build.opensuse.org/package/live_build_log/home:lukho:copyq/CopyQ/xUbuntu_16.04/x86_64).

**Comment by nemonein** [comment]
It's been successfully built(http://download.opensuse.org/repositories/home:/lukho:/copyq/xUbuntu_16.04/amd64/) but it's not installable, because of libqt4-gui, which is no longer supported on Ubuntu 16.04.

I removed 'libqt4-gui' from debian.control file(https://build.opensuse.org/package/view_file/home:lukho:copyq/CopyQ/debian.control?expand=1), and built it, and it was successful. Of course I could install it.

I read that libqt4-gui is just a dummy package, and all other packages(libqt4-xml, libqt4-network, libqt4-script, libqt4-svg) are clearly specified on debian.control, I think it's ok to remove libqt4-gui.

So far, CopyQ works fine for me.

**Comment by GrouchyGaijin** [comment]
@nemonein Thank you so much!

**Comment by hluk** [comment]
@nemonein Thanks for the info -- I've removed the `libqt4-gui` runtime dependecy. It seems that building for Ubuntu 16.04 was just broken on OBS initially.

I've uploaded the packages [here](https://github.com/hluk/CopyQ/releases/tag/v2.6.1).

I didn't manage to find Qt WebKit build dependency so Web plugin will be missing meaning you will see only basic HTML rendering in CopyQ.

**Comment by orschiro** [comment]
Thanks to all of you for your work to making CopyQ available on Ubuntu 16.04!

**Comment by nemonein** [comment]
@hluk I don't know what you meant `Qt WebKit build dependency`, but there is `libqtwebkit-dev` (and  `libqtwebkit4' too) Ubuntu 16.04. I tried to add this on debian.control file, and building was successful.

Did you mean this?

**Comment by hluk** [comment]
@nemonein On OBS there are no such packages - perhaps just yet.

**Comment by junkystu** [comment]
I am still unable to install on 16.04 because it still depends on `libqt4-svg`

**Comment by orschiro** [comment]
@junkystu can you install the package from here?

http://packages.ubuntu.com/search?keywords=libqt4-svg

**Comment by nemonein** [comment]
`libqt4-svg` is on the Ubuntu 16.04.

```
$ apt policy libqt4-svg
libqt4-svg:
  Installed: 4:4.8.7+dfsg-5ubuntu2
  Candidate: 4:4.8.7+dfsg-5ubuntu2
  Version table:
 *** 4:4.8.7+dfsg-5ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

If you have used dpkg, please try this again.
```
$ sudo dpkg -i copyq_2.7.1_Ubuntu_16.04_amd64.deb
$ sudo apt install -f
```

I hope this would help you.

**Comment by junkystu** [comment]
@nemonein Thank you, that did it. I have tried forcing it before but the icon in the toolbar was coming up with a forbidden sign. I've removed and installed again and this time it worked fine.

@orschiro I have looked over there before but I missed the first time due to being in a rush and looking for "16.04" rather than "xenial"

**Comment by nemonein** [comment]
I opened a ppa for copyq. (not just for the copyq, actually.)
I included the libqtwebkit-dev when building.
Only Xenial version is in the PPA.
https://launchpad.net/~nemonein/+archive/ubuntu/tailored
