### ISSUE TITLE
Can't paste into Firefox fields

### ISSUE THREAD

**Issue by SinfulSaint** [hluk/CopyQ#505]
Hello all!

Could anyone tell me why copyq can't paste text into Firefox fields (website forms, username, password fields) after I perform a double-click operation? Paste into current window option under history tab is enabled.

I can normally paste text into e.g. notepad, word, excel after a double-click operation.

Thanks!

**Comment by hluk** [comment]
Cannot reproduce this on Windows 8.1 and Linux (i3 window manager).

Can you provide more info about your OS, Firefox and web page where this can be reproduced?

**Comment by SinfulSaint** [comment]
Hey hluk!

None of the fields work. Google search field and www address field alike. Even tried some random pages. No go. 
IE11 works fine.
It's W10 64bit. Firefox 46.0.1

Installed copyq on my laptop. Same OS, same Firefox. No luck.

**Comment by scottkosty** [comment]
@SinfulSaint , just curious---does it work with Chromium?

**Comment by SinfulSaint** [comment]
Don't know, really. Might give it a try later or see if it works on a W7 machine today.

**Comment by hluk** [comment]
I tried Firefox 46.0.1 on Windows 10 and pasting seems to work with CopyQ 2.7.0.

I think it could be an add-on that is messing with the focusing.

**Comment by SinfulSaint** [comment]
Works fine with W7, same FF version. Might give it a look later. 
Thanks Lukas. Great little program. 
I have a few suggestions though. I believe it would need a different post here.

**Comment by scottkosty** [comment]
@hluk in theory, isn't it possible that two different hardware configurations that have the exact same software image (e.g. same OS and same installed software) have different results (e.g. CopyQ successfully pastes into a window on one system and not on another system) because CopyQ relies on an absolute delay (e.g. https://github.com/hluk/CopyQ/commit/af4a2f24e1eaceee304ce5b028aefa20e2f27b1f)? For example, on the faster machine the window manager might switch windows quicker and bring Firefox into focus slightly quicker and thus be ready for the paste quicker than the slower hardware system. 

I'm just curious if my understanding is correct.

**Comment by hluk** [comment]
@scottkosty It's possible. Some delay needs to be added when sending key press events and focusing some windows. I haven't find a better way to do this.

**Comment by scottkosty** [comment]
Makes sense. Yes from what I understand CopyQ does everything it can. I just wanted to make sure I understood the situation.
