### ISSUE TITLE
Consecutive invocation of series of "paste and copy next" commands pastes wrong text

### ISSUE THREAD

**Issue by hluk** [hluk/CopyQ#516]
Invoking  "paste and copy next" second time after new text is copied pastes wrong text (selection in item list is wrong).

Seems to happen only if the main window is hidden (on Windows).

**Comment by scottkosty** [comment]
On Ubuntu, for me it also happens when the main window is shown. When I was writing the initial recipe to reproduce, I had vim on the left side of my screen and CopyQ on the right, in order to see what was going on. Out of 4 times, I was not able to reproduce once though, so perhaps it does depend on something.
