### ISSUE TITLE
Will not open or install a new version!

### ISSUE THREAD

**Issue by mymonaro** [hluk/CopyQ#526]
I loved this program until recently. It was working on Windows 10, but now when I attempt to open the program it will not open. It will appear to be running in the background processes. I have uninstalled the program and downloaded the latest version. I attempt to run the installation file, but nothing will happen. How can I get back to using this great program?

**Comment by scottkosty** [comment]
Did anything else change on your system? Can you try an older release and see if that works for you? If it does, that will help narrow down what the problem might be.

**Comment by mymonaro** [comment]
Thanks for the reply.

When I went to use the program this morning it was a version which had been installed on my computer since last December which would not run. I then uninstalled it and attempted to install the latest version but it would not do anything.

**Comment by mymonaro** [comment]
Thanks for the reply.
When I went to use the program this morning it was a version which had been installed on my computer since last December which would not run. I then uninstalled it and attempted to install the latest version but it would not do anything.
Regards,Geoff
 

    On Wednesday, 6 July 2016, 14:37, Scott Kostyshak <notifications@github.com> wrote:
 

 Did anything else change on your system? Can you try an older release and see if that works for you? If it does, that will help narrow down what the problem might be.—

**Comment by scottkosty** [comment]
I would recommend the following (but please see disclaimer below): exit CopyQ (or kill it if you cannot exit it yourself), move CopyQ's .config folder where it stores data (key word is move, not delete, so that you can always move it back if something is broken). Then restart your computer and see if CopyQ works then. I don't know where the config folder is on Windows. On Ubuntu it is in `~/.config/copyq`. Perhaps you can search for the file `copyq.conf` and that will lead you to the folder.

The above advice is just what *I* would do. Since I always get confused by Windows' behavior, I'm hesitant to recommend anything to you. You might want to wait until someone more knowledgeable about Windows comes along.

**Comment by mymonaro** [comment]
Thanks for the reply.
 

    On Wednesday, 6 July 2016, 18:20, Scott Kostyshak <notifications@github.com> wrote:
 

 I would recommend the following (but please see disclaimer below): exit CopyQ (or kill it if you cannot exit it yourself), move CopyQ's .config folder where it stores data (key word is move, not delete, so that you can always move it back if something is broken). Then restart your computer and see if CopyQ works then. I don't know where the config folder is on Windows. On Ubuntu it is in ~/.config/copyq. Perhaps you can search for the file copyq.conf and that will lead you to the folder.The above advice is just what I would do. Since I always get confused by Windows' behavior, I'm hesitant to recommend anything to you. You might want to wait until someone more knowledgeable about Windows comes along.—
