### ISSUE TITLE
Maximum number of items in history?

### ISSUE THREAD

**Issue by orschiro** [hluk/CopyQ#600]
Hello all, 

Can I use CopyQ to create an archive (backup) of my historical use?

How many items can I store at most?

![image](https://cloud.githubusercontent.com/assets/170947/20974679/5a74ed74-bc9d-11e6-9c3e-e6b8c7166311.png)

**Comment by neojski** [comment]
See also #510.

**Comment by hluk** [comment]
Maximum number of items per tab is 10,000.

With an automatic command it should be possible to create new tabs to backup old items that would be otherwise deleted or mirror adding clipboard to other tab. I'll try to post a command in #510 if I come up with anything good.

For me the best way is to create few automatic commands to organize items similar to "Copy URL (web address) to other tab" or [Copy Clipboard to Window Tabs](https://github.com/hluk/CopyQ/wiki/Command-Examples#copy-clipboard-to-window-tabs).

**Comment by neojski** [comment]
Could you just add a checkbox that would say "Unlimited number of items in history"?

**Comment by hluk** [comment]
@neojski Current architecture doesn't support unlimited number of items. All items from current tab are loaded to memory so the application would just crash with insufficient memory at some point.

It's not an easy task to implement this -- I would need to use another format to store items (probably SQL database as mentioned in #510) and reimplement the list widget in GUI.
