### ISSUE TITLE
Problems on MacOS Sierra 10.12.1 (16B2555)

### ISSUE THREAD

**Issue by fillipvt** [hluk/CopyQ#603]
![image](https://cloud.githubusercontent.com/assets/16828078/21280731/bea18ebe-c3b5-11e6-8fec-bb94ea2cb29c.png)

After copying [this image](http://www.pngall.com/wp-content/uploads/2016/04/Rose-Free-Download-PNG.png) CopyQ closed with out errors, but after starting it again, [this happened](http://waggl.io/2H1H1U2w160I). 

All GUI becomes unresponsive up until CopyQ closes itself. This happens again and again.

What information can I supply to pinpoint this problem?

**Comment by hluk** [comment]
Seems there are problems when reading larger amount of data. I'll try to fix it ASAP.

**Comment by hluk** [comment]
I fixed some issues related to copying big data. Can you check if it's fixed with [this package](https://github.com/hluk/CopyQ/releases/download/untagged-ecd4b0d73ac9170ef5cf/CopyQ.dmg)?

If it's not fixed can you provide log file? If possible you can print log file location with `copyq info log` command when app is launched -- could be something like `/Library/Application Support/copyq/copyq/copyq.log`.

**Comment by fillipvt** [comment]
@hluk problems with large images seems to be fixed! I'll reopen in case of any other bug related to this matter. Sorry for taking this long to respond.
