### ISSUE TITLE
Synchronize clipboard across computers using Dropbox: limitations

### ISSUE THREAD

**Issue by dasebasto** [hluk/CopyQ#618]
There seems to be 2 ways to synchronize clipboard across computers:

**Solution 1): Use Item > Synchronize menu to sync `&clipboard` tab to a Dropbox folder.**
Limitations:
- filename clutters the display (it should be optional)
![image](http://i.imgur.com/TppoFaw.png)
- it's impossible to exclude certain files based on type or size: obviously I don't want big files I copy to end up duplicated in my Dropbox folder --> syncing *only* text and rich text to Dropbox would be enough for me. But ideally I would like to still keep the big files in my history on the "source computer"...

Am I missing something?

**Solution 2): Use portable CopyQ and store inside a Dropbox folder**
I have not tested this.
Is this supposed to work?
Can CopyQ detect external changes made to its data And refresh accordingly?

Thanks for the great work!

**Comment by hluk** [comment]
Ad 1.
- Generated file names will be removed in next version ([beta is here](https://ci.appveyor.com/project/hluk/copyq/build/1.2.595/job/7fl85b5n1nbqqiis/artifacts)).
- You can omit storing anything else then text in clipboard tab with a command. E.g. I use following to move images to different tab.

```ini
[Command]
Automatic=true
Icon=\xf03e
Input=image/png
Name=Move Images to Separate Tab
Remove=true
Tab=&Images
```

Ad 2. This would probably not work. The application is designed so that one configuration folder is used only by single instance of the app.

**Comment by dasebasto** [comment]
Excellent, thank you hluk.

I had not fully understood how commands worked, but I know realize their potential!
