### ISSUE TITLE
Silent install can't close application

### ISSUE THREAD

**Issue by majkinetor** [hluk/CopyQ#638]
Hi there, 

I am maintainer of the chocolatey package for WIndows

As of recently, updater fails to close CopyQ so update process hangs until it timeouts:

https://github.com/majkinetor/au-packages/issues/30

To overcome this user must explicitly exit the CopyQ. This didn't happen before and started recently.

I can kill the process as a workaround before I run the update, is that safe ? Or perhaps this should be handled in the installer itself.

**Comment by hluk** [comment]
I think this is bug in installer or Qt. I've been trying to solve it without success (#591) -- I finally closed the bug since I couldn't fix it properly and it didn't seem that important because installer prompts user to close the app.

Killing the app might mean it looses some data or forcefully closes editor. I'll try to look more into it this week -- I'll try to use different installer if nothing else helps.

**Comment by hluk** [comment]
BTW, `/FORCECLOSEAPPLICATIONS` installer argument should kill the application. But as I said it could be unexpected for user.

**Comment by hluk** [comment]
It's fixed except when tray is disabled :(.

**Comment by majkinetor** [comment]
That is serious BS with tray :)

While I understand the concern, I think tray problem could safely be ignored.
I seriously doubt there are many people that use CopyQ in combination with Chocolatey and have its tray icon disabled. If they don't use choco then they are manually updating in which case its not important at all.

If I find any problem in the future regarding to this (will see when new update lands) I will give feedback here. I will close this now since solution is good for me.
