### ISSUE TITLE
Menu flicker when called if CopyQ wasn't running

### ISSUE THREAD

**Issue by ZIEXED** [hluk/CopyQ#645]
After upgrading from 2.8 to 2.9 calling the menu while copyq isn't running cuase it to flicker twice

_I think this is due to the new "Search items from tray menu" feature since v2.8.3_

**Comment by hluk** [comment]
I don't have this problem on Windows 8.

Does "copyq isn't running" mean that the main application window is not visible?

In v2.9.0 the flickering should be less apparent because the menu is not updated when visible unless you start searching items -- and there are some workarounds to avoid flickering when searching.

**Comment by ZIEXED** [comment]
> 	If !ProcessExist("copyq.exe")
> 	{
> 	Run, P:\CopyQ\copyq.exe
> 	Sleep, 100
> 	Run, P:\CopyQ\copyq.exe menu

in version 2.8 this works great
in latest version this cuase the menu to flicker and I need to wait for 1 sec before calling the menu to appear without flicker
I hope you can eaisly fix it

**Comment by ZIEXED** [comment]
Awesome! Thank you ♥

**Comment by hluk** [comment]
Fixed version should be [here](https://ci.appveyor.com/project/hluk/copyq/build/job/xh621veaayinvl30/artifacts) any moment so you can test it.

**Comment by ZIEXED** [comment]
Fix confirmed
Thanks again :)
