### ISSUE TITLE
How can I make the duplicate Auto-deleting still effective while using Write()?

### ISSUE THREAD

**Issue by marqqer** [hluk/CopyQ#650]
Hi dear Hluk:
I have a command:
```
[Command]
Name=Remove uri-list ended line breaks and mark the item
Command="
    copyq:
    var color = 'rgba(196,248,192,0.5)'
    var time = 'Copy Time: '+dateString('yyyy-MM-dd hh:mm:ss')
    var text=decodeURI(str(input()).replace(/\\n$/g, ''))
    write(0,
      'text/uri-list', input(),
      'text/plain', text,
      'application/x-copyq-color', color,
      'application/x-copyq-item-notes', time
      );"
Input=text/uri-list
Automatic=true
Transform=true
Enable=false
Icon=\xf06a
```
My destination is to remove the last \n when copying multi Items and decodeURI to show right name and mark the item with a different Color.
My question is:
1. Before adding any clip to History , CopyQ  do an automatic search to remove identical clips .but if I use the   write() to add data ,the Duplicate Auto Deleting will not work,How can I modify the command to make it still effective?
2. How can I mark the Item by changing the Font color rather than changing the Background color?
3. I think  CopyQ  should do the work of removing last \n and decodeURI when save the item to history . 
You may find that when copying multi files ,CopyQ will show an extra line break in the History and if the file name contains "%" "{" "}" the listed name in history will not be displayed correctly .
4. It is much preferable If CopyQ provides an option to set color to  item of different type (text/uri-list/text/xml/text/plain...) , Items of different type would be distinguished more easily.

Thanks and best wishes

**Comment by hluk** [comment]
ad 1. Instead using `write()` use `setData()` in automatic items.

```js
setData(mimeUriList, input())
setData(mimeText, text)
setData(mimeColor, color)
setData(mimeItemNotes, time)
```

Next automatic commands will receive the updated data (not the original clipboard data) and this data will also be saved in the list.

Unfortunately, since the copy time in note differs, CopyQ won't replace existing item with same text.

BTW, you can use [tag to store copy time](https://github.com/hluk/CopyQ/wiki/Command-Examples#show-copy-time). Tag don't take that much space as notes and you can still add custom notes.

ad 2. You can add HTML to change the item style.

```js
var html = '<p style="color: red; font-weight: bold">' + escapeHtml(text) + '</p>'
setData(mimeHtml, html)
```

ad 3. I'll test and fix the issue if possible.

ad 4. I've been thinking about adding a feature that would allow user to change item appearance depending on content. Not yet sure how to implement it.

**Comment by marqqer** [comment]
Thank,got it.
I tested the command and finaly  found a workable version by set 'Transform=false'
```
[Command]
Name=Remove uri-list ended line breaks and mark the item
Command="
    copyq:
    var color = 'rgba(196,248,192,0.5)'
    var text=decodeURI(str(input()).replace(/\\n$/g, ''))
    setData(mimeUriList, input())
    setData(mimeText, text)
    setData(mimeColor, color)"
Input=text/uri-list
Automatic=true
Icon=\xf06a
```
