### ISSUE TITLE
When using global shortcut to "Show/hide main window" on Mac, the main window opens on primary desktop

### ISSUE THREAD

**Issue by findepi** [hluk/CopyQ#654]
## steps

1. using mac sierra ...
1. having configured CopQ: History > "close main window" & "focus last window"
1. open a web browser window
1. configure global shortcut for "Show/hide main window", i use `ctrl cmd V` for that
1. press the shortcut
1. when the main CopyQ window appears, close it
1. open another desktop and a new window for the web browser there
1. press the shortcut again

## expected

* main CopyQ window, on current desktop
* when I select something from the history, focus should return to the web browser window on the second desktop

## observed

* main CopyQ window, on first desktop
* even after selecting something from the history, focus doesn't return to second desktop

**Comment by findepi** [comment]
On Windows and Linux, using "Show/hide main window" with a global shortcut is probably the most convenient way to search&select from clipboard history. On Mac this doesn't seem to work so smoothly. Perhaps it doesn't to, but what shall I be using instead?

**Comment by hluk** [comment]
I don't know how desktops work on Mac (unfortunately I cannot test this). Perhaps this is bug in Qt.

You can try "Show main window under mouse cursor" to open the main window if it solves this issue.

BTW, command "Show the tray menu" supports searching items since version 1.9.0 and if you change the command to (enable "Show Advanced" check box first):

```js
copyq: menu('clipboard')
```

only items for "clipboard" tab will be visible without any additional menu actions.

**Comment by findepi** [comment]
"Show main window under mouse cursor" seems to do the trick. Thanks!

**Comment by findepi** [comment]
"Show the tray menu" _looks_ even better. It open a very nice floating menu, but apparently it doesn't grab focus and neither up/down arrows nor searching are render unavailable. But it always opens in the right place :)
