### ISSUE TITLE
CopyQ crashes Excel when copying from Show Formulas 

### ISSUE THREAD

**Issue by ScottRochford** [hluk/CopyQ#666]
This could be an Excel issue of course, but... Excel 2013, CopyQ 2.5.0, Windows 7 Enterprise 64-bit.  

Ctrl-~ to switch Excel to "Show Formulas" mode, select any cell containing a formula, Ctrl-C, Excel crashes.

If I exit CopyQ, it works normally.

Is it just me?

**Comment by ScottRochford** [comment]
I just realised that CopyQ 2.5.0 is quite old and updated to 2.9.0, but the result is the same.

**Comment by hluk** [comment]
This could be similar to issues #580 and #613 -- CopyQ is asking for too much data which can lead to app freezes or even crashes.

Try to disable "Images" and "Data" in "Items" tab in Configuration dialog.

![image](https://cloud.githubusercontent.com/assets/38054/23902376/2c774c08-08c1-11e7-9dfe-ce0f1c7280b9.png)

I should probably fix this so that image and other data are ignored if there is text in clipboard.

**Comment by ScottRochford** [comment]
Yes, that does prevent the crash occurring - thanks for the workaround.

**Comment by scottkosty** [comment]
After c7b28c8 copyq no longer saves a format I specify (in preferences under items > data) because that format happens to be be stored along with text. The format is application/x-lyx. In the chunk added at c7b28c8, can we add an exception for formats that are specified to save in history?

**Comment by hluk** [comment]
@scottkosty OK, fixed in eac0c57d (omits only images when text is available).

**Comment by scottkosty** [comment]
@hluk thanks for the quick fix, works well.
