### ISSUE TITLE
Syncronize item and history limit = Tab is Full.

### ISSUE THREAD

**Issue by ipleten** [hluk/CopyQ#687]
When I enable synchronize 
"&clipboard" => /home/user/copy_q/clipboard
 and limit history to 30 
 I get "Tab is full..."  when try to copy 31 times :) (mouse selection is enabled) 

After if I disable synchronize item app crashed and won't start with:

> ~$ copyq 
ERROR: Item file “/home/user/.config/copyq/copyq_tab_JmNsaXBib2FyZA==.dat” is corrupted or some CopyQ plugins are missing!
Segmentation fault (core dumped)

> ~$ copyq --version
CopyQ Clipboard Manager v3.0.0 (hluk@email.cz)
Built with: Qt 5.5.1, LibQxt 0.7.0

> ~$ cat /etc/issue
Ubuntu 16.04.2 LTS \n \l

**Comment by hluk** [comment]
I fixed the crashing.

If you disable synchronization plugin, the tab won't be loaded since the plugin handles the tab data. You would need to remove the tab from plugin's configuration.

Workaround for now is to re-enable the plugin: Edit `~/.config/copyq/copyq.conf` and change line `itemsync\enabled=false` to `itemsync\enabled=true`.

Not sure how to better handle adding new items to synchronized tab. Removing files if the tab limit is exceeded may be unwanted behavior -- I often synchronize tabs with existing documents which I want to be removed only with an explicit action.

It may be better to leave the files on disk and just remove items in CopyQ, but it may lead to too many files in synced directory.

Other solution is to use automatic command which moves files to different folder if tab is full.

**Comment by hluk** [comment]
Version with fixed crashing is [here](https://ci.appveyor.com/project/hluk/copyq/build/1.2.965/job/cl2ky96skqhwyhrq/artifacts).

I'm not sure how to handle full synced tab yet.

**Comment by hluk** [comment]
The synced items created by CopyQ can now be removed without confirmation (with `copyq_*` files) -- works the same for non-synchronized tabs.

The confirmation dialog for deleting item only pops up if the underlying files were not created by CopyQ. This is just a safety measure against accidental removal of some important files.

Also "Tab is full" message shouldn't popup in most cases.

See also #712.
