### ISSUE TITLE
How to get %1 in perl?

### ISSUE THREAD

**Issue by eexpress** [hluk/CopyQ#699]
when use perl:

```
perl:
$_=`copyq read 0`;
.....;

```
`copyq read 0` take the last exist item in history, not the current copied one.
of course, `$_=%1` take nothing. %1 is perl internal parameter. `$_=shift` take nothing.

**Comment by hluk** [comment]
If you set "Format" field for the command you can read the data from stdin in Perl (`<>`).

**Comment by eexpress** [comment]
$_=<STDIN>;
can work. just seems some strange. `shift` no work. %1 is not pass as parameter?

**Comment by hluk** [comment]
Expression `%1` works only if you use simple commands, e.g. `notify-send %1` or `perl -e 'print($ARGV[0])' -- %1`.

Anyway, passing data on stdin is much better since there is size limit in system for command line with arguments.

BTW, you can access other command data and selected items from more complicated commands, e.g.:

```bash
bash:
html=$("$COPYQ" data text/html)
selected=( $("$COPYQ" selectedItems) )
first_selected="${selected[0]}"
```
