### ISSUE TITLE
Command with regex for matching content only triggers on Ctrl-C and not on mouse selection

### ISSUE THREAD

**Issue by eguendelman** [hluk/CopyQ#723]
I enabled both "Store clipboard" and "Store text selected using mouse", and both types of content is added to the CopyQ buffer.  But if I configure a custom command with a regex for matching content, this only seems to apply to the last item copied with Ctrl-C and not to any item just selected with mouse.  Is this expected behavior?
Thanks

**Comment by hluk** [comment]
Can you share the command here? BTW, only "In Menu" commands can work with item selection -- "Automatic" and "Global Shortcut" commands work with current clipboard content.

**Comment by eguendelman** [comment]
Okay, here's a concrete example, though it happens with any regex or command body:
Create a new command, of type "In Menu", for content matching write `^http`, and for the command body write `copyq popup %1`. 
So if you copy to clipboard (using Ctrl-C) text that starts with http, you will see the command in the CopyQ menu.  If the text doesn't start with http, the command won't show up.
*but* if you use unix-style mouse selection (without Ctrl-C) to select text starting with http (and have "Store text selected using mouse" checked), you will see the selected item show up in CopyQ's list of items properly, yet the command won't appear in the menu...
Conversely, if the last thing you Ctrl-C'd to the clipboard starts with http, and now you use unix-style mouse selection to select that doesn't start with http, the command will remain in the CopyQ menu because it is still comparing the regex to the last item in the Ctrl-C clipboard and ignoring the newer item that came in through the mouse selection. 
Hope that makes sense.  I believe it should be easily reproducible.  Just wondering if this is expected behavior.

P.S. are you saying "global shortcut" can't be used with unix-style selected items, or are you referring to something else when you say "item selection"?

Thanks

**Comment by hluk** [comment]
> P.S. are you saying "global shortcut" can't be used with unix-style selected items, or are you referring to something else when you say "item selection"?

I was referring to the item selection in the application.

Still, "Content" field for "Global Shortcut" commands is applied on clipboard data and not the mouse selection buffer nor the selected items.

This is actually the same behavior for **"In Menu" commands in tray menu** -- since you cannot select items from the tray, the "Content" regex matches clipboard (you can see what it matches in tray menu as `Clipboard: ...`).

To match mouse selection from tray menu you either need to **set "Paste mouse selection with clipboard" option** (in "General" config tab) or set "Filter" field in the command to e.g.

```js
copyq: str(selection()).match(/^http/) || fail()
```

and use `copyq: ... selection() ...` in command instead of (`%1` or `input()`).
