### ISSUE TITLE
Feature Request - Add Hover for right-mouse clipboard history

### ISSUE THREAD

**Issue by richlux** [hluk/CopyQ#726]
Would it be possible to add a hover-over when moving the mouse over the clipboard history that is shown when you right-mouse click the CopyQ icon?  The hover would show the entire formatted clipboard entry with images, similar to what you get when you open the CopyQ window with the left-mouse click.  Currently, it's difficult to determine what was copied without being able to see the entire text or larger image.

Thanks,
Rich

**Comment by hluk** [comment]
This is difficult to implement for all supported platforms. OS X and most desktop environments on Linux handle the tray menu themselves.

Similar feature had been used to show tool tips for notes near items in tray menu. But this was removed because it either didn't work in some environments or it misbehaved.

If you need to show whole items open main window instead - I find it often easier to use than the menu.

See: [How to open application window or tray menu using shortcut?](https://copyq.readthedocs.io/en/latest/faq.html#how-to-open-application-window-or-tray-menu-using-shortcut)
