### ISSUE TITLE
A pathname instead of text pasted after CTRL+C / CTRL+V or double click, when I copy it from a  tab that is linked to a folder on Ubuntu 16.04

### ISSUE THREAD

**Issue by ocoka** [hluk/CopyQ#741]
![image](https://user-images.githubusercontent.com/8239290/27849323-03f9f28e-6155-11e7-9f85-260a8a918a87.png)

It's about *GNOME Terminal*, some text editor pasted as plan/text

Ubuntu 16.04 64bit
CopyQ Clipboard Manager v3.0.3 (hluk@email.cz)
Built with: Qt 5.5.1, LibQxt 0.7.0

**Comment by ocoka** [comment]
Maybe a duplicate of a #702

**Comment by hluk** [comment]
Seems like bug in GNOME Terminal. It ignores `text/plain` format and uses raw `text/uri-list` instead.

Not sure if I can fix this in CopyQ. Ignoring `text/uri-list` would work in the terminal but it would break pasting the files in file managers.

Using <kbd>Shift</kbd>+<kbd>Insert</kbd> works since it inserts content of X11 selection buffer.

Drag'n'drop seems also buggy the terminal -- it inserts only the first URI from the list and it ends with line break.

As a workaround you can use following command which overrides the default copy action.

```ini
[Command]
Command="
    copyq:
    var shortcut = str(data(mimeShortcut))
    
    if (shortcut == 'enter' || shortcut == '') {
      if (config('hide_main_window') == 'true')
        hide()
    
      copy(input())
    
      if (config('activate_pastes') == 'true')
        paste()
    } else {
      copy(input())
    }"
Icon=\xf0ea
InMenu=true
Input=text/plain
MatchCommand=copyq: read('application/x-copyq-itemsync-basename') || fail()
Name=Copy Text (Ignore URI)
Shortcut=enter, ctrl+c
```
