### ISSUE TITLE
Cannot copy/paste/preview image

### ISSUE THREAD

**Issue by karakatsanism** [hluk/CopyQ#752]
Hello, I am having a problem copying/pasting and previewing images in copyq. When I am trying to copy a picture (png OR jpg) it stores them as file:///... text and there is no preview available.

I am using latest version of copyq (3.0.3) and Windows 10 64-bit. Also, I am using [Honeyview](https://www.bandisoft.com/honeyview/) as my default image viewer.

Any thoughts?

**Comment by hluk** [comment]
Seems like the file path is copied instead of the image (this is normal behaviour in file browsers). CopyQ only shows image preview when actual image is available.

You can use following command to add the preview ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)).

```ini
[Command]
Automatic=true
Command="
    copyq:
    var height = 200
    var filePath = str(input())
    
    setData(mimeHtml,
      '<img height=\"' + height + '\" src=\"' + filePath + '\" />'
      // Show path.
      + '<div style=\"margin-top: 4px\">'
      + escapeHtml(data(mimeText))
      + '</div>'
    )"
Icon=\xf03e
Input=text/uri-list
MatchCommand=copyq: new RegExp('^file:///.*\\.(jpg|png|gif|bmp)$').test(str(data(mimeUriList))) || fail()
Name=Preview Image Files
```

**Comment by smaragdus** [comment]
**@hluk**
_Off-topic_
Is there a way to add "paste current date and time" command?

**Comment by hluk** [comment]
Yes, [Paste Current Date and Time](https://github.com/hluk/copyq-commands/tree/master/Global#paste-current-date-and-time). :)

**Comment by smaragdus** [comment]
**@hluk**
Thank you very much for the tip!
I modified this line:
`copy('Current date/time is ' + time)`
to
`copy(time)`
to paste just the date and time, without "Current date/time is ".
I asked because this command was not available in "File" - "Commands/Global Shortcuts' - "CopyQ Add Commands". Shouldn't "Paste Current Time" command be present in the commands list?

**Comment by karakatsanism** [comment]
:grateful:
😃

**Comment by hluk** [comment]
@smaragdus You can now select the command in CopyQ. Though one difference is that the default format depends on the current system language.
