### ISSUE TITLE
Doubled ampersands in desktop applet's drop down menu

### ISSUE THREAD

**Issue by MrksKwsnck** [hluk/CopyQ#764]
I am using CopyQ v3.0.3 installed on Ubuntu Budgie 17.04 Zesty Zapus.

When copying an ampersand (e.g. "Tom & Jerry") to the clipboard, in the desktop applet drop down menu the ampersand is shown twice then (e.g. "Tom && Jerry").

![image](https://user-images.githubusercontent.com/486983/29458302-ae9f2eac-841e-11e7-9159-86d2c55b7f4f.png)

Though pasting the copyied text results correctly with one ampersand only. So I suppose it's just an interface view issue.

**Comment by hluk** [comment]
I cannot test this properly but looks like a bug in Qt.

For menu items, character after `&` is used for mnemonics, i.e. `&Help` would show up in menu as "Help" with underlined "H" and the menu item can be quickly accessed by pressing <kbd>H</kbd> key.

Special case is `&&` which just shows up as single `&` without any mnemonic being created. But in this case it doesn't work. I think the problem is in qtbase code in function [QDBusMenuItem::convertMnemonic()](https://code.qt.io/cgit/qt/qtbase.git/tree/src/platformsupport/themes/genericunix/dbusmenu/qdbusmenutypes.cpp?h=5.9.0#n224).

**Note:** This was handled properly with [libdbusmenu-qt](http://bazaar.launchpad.net/~dbusmenu-team/libdbusmenu-qt/trunk/view/head:/src/utils.cpp?start_revid=271) which was needed for older Qt version.

Can you submit a [bug report for Qt](https://bugreports.qt.io)?
