### ISSUE TITLE
Enable GPG in ZIP distro

### ISSUE THREAD

**Issue by vatterspun** [hluk/CopyQ#823]
Setup: Win7x86

Steps: 
1. Download the ZIP version of CopyQ
2. Install GPG4WIN (I skipped the outlook plugin because I don't use it) as described here https://copyq.readthedocs.io/en/latest/password-protection.html
3. Restart CopyQ

Defect: GPG doesn't seem to be enabled

* When selecting Encrypt from the menu, get the following error

![image](https://user-images.githubusercontent.com/1289134/31856917-9e685ca4-b694-11e7-962b-caad5261d1c2.png)

* The **Preferences - Items - Encryption** menu is the same:

![2017-10-21 18_40_43-copyq configuration](https://user-images.githubusercontent.com/1289134/31856918-a7e95418-b694-11e7-9865-c62ef065ea17.png)

**Other notes**: In the screen I listed above, it makes reference to a "Commands" tab.  I think it's now the "Shortcuts" tab.

**Comment by hluk** [comment]
Works with Gpg4win 2.3.3.

Gpg4win 3.0.0 installation is missing "gpg2.exe" - no idea why.

The encryption plugin in CopyQ only requires a compatible version of "gpg2" utility to be in available PATH. It also assumes that the utility can use GUI password entry dialog (usually [pinentry](https://gnupg.org/software/pinentry/index.html)).

**Comment by vatterspun** [comment]
> The encryption plugin in CopyQ only requires a compatible version of "gpg2" utility to be in available PATH. 

Oh yeah, I hadn't thought of that.

> Gpg4win 3.0.0 installation is missing "gpg2.exe" - no idea why.

Weird.

**Comment by hluk** [comment]
Gpg4win (3.0.0 and newer) stopped providing `gpg` utility needed by CopyQ.

As workaround, instead of the classic Gpg4win you can install [gpg4win-vanilla](https://chocolatey.org/packages/gpg4win-vanilla) or older Gpg4win (2.3.3). I've just fixed this in [the documentation](http://copyq.readthedocs.io/en/latest/password-protection.html).

Some additional fixes are required in new version of CopyQ. You can install the fixed version from [here](https://ci.appveyor.com/project/hluk/copyq/build/job/70w382ytw1xmbv0g/artifacts).
