### ISSUE TITLE
Is there a way to use Abbreviation feature?

### ISSUE THREAD

**Issue by nemonein** [hluk/CopyQ#861]
Thank you for your great software.

I wonder there could be a way to use abbreviation in CopyQ.
'Abbreviation', such as the one in [VIM](http://vim.wikia.com/wiki/Using_abbreviations).
In VIM,
```
:ab rtfm read the fine manual
```

Any ideas are welcome.

**Comment by hluk** [comment]
How would it be used? Or do you mean just in FakeVim mode when internal editor is open?

**Comment by nemonein** [comment]
Thanks for your reply.
I mean, I would like to use it in every application.
I use [Autokey](https://github.com/autokey/autokey/) for this feature, but it does not support Wayland.

I wonder if you have any opinion about this feature.
Thanks!

**Comment by hluk** [comment]
I think this was requested before. It would be very difficult to implement on all supported systems (Wayland itself doesn't allow keylogging, so it would need to be bypassed).

So it's probably not going to happen.

**Comment by m4r71n** [comment]
I'm using the Snippet command to paste expanded abbreviations. Take a look on this gist and the comments: https://gist.github.com/hluk/af37cd2ca650c92ed0fa

**Comment by hluk** [comment]
More up-to-date version of Snippets command is available [here](https://github.com/hluk/copyq-commands/tree/master/Global#snippets) (see [README](https://github.com/hluk/copyq-commands/blob/master/README.md) on how to add commands).

Though this may not be so comfortable to use since it takes focus away from editor momentarily.

Also I expect it may not work well in some apps since there is no native support for pasting text from CopyQ for Wayland.

**Comment by m4r71n** [comment]
> Also I expect it may not work well in some apps since there is no native support for pasting text from CopyQ for Wayland.
Thanks, I didn't know.
