### ISSUE TITLE
Save to user tab when you press global hotkey

### ISSUE THREAD

**Issue by User3985** [hluk/CopyQ#873]
The global shortcut should help group the data during the copy operation. 
When you press one of the hot keys, the data is copied to the tab assigned to the hotkey.
Based on the examples, I created the following script:

 [Command]
Name=1
Command="
    
    copyq:
        tab(1);
        copy();
        var text = str(clipboard());
        write(
     index(),
    'text/html', text,
    'text/plain', text
    );
    
    "
Remove=true
Icon=\xf064
Shortcut=alt+1
GlobalShortcut=alt+1
Tab=1

This script works, but copies only text data.
Sometimes the data is not copied and an error is displayed:

 `Command «1»
 Exit code: 4

  ScriptError: Failed to copy to clipboard!
 --- backtrace ---
  <eval>() at «...»:3
 --- end backtrace ---`

**Win10/64, 3.1.2** 

Thanks for the help and for the unique clipboard manager which works with multiple tabs and global hotkeys.

**Comment by hluk** [comment]
Few notes:
- `copy()` - this sends <kbd>Ctrl</kbd>+<kbd>C</kbd> shortcut to current window to copy, **this can indeed fail**, depending on the active application (if CopyQ won't detect clipboard change this throws an exception, leading to the error)
- `index()` - this returns currently selected item but works only if command is run from menu, this returns -1 if called from global shortcut command
- `write(...)` - since the index is -1, it appends item to current tab (which is "1"); you shouldn't set HTML format to plain text since it can be malformed HTML
- you can use `str(data(mimeShortcut))` to access the global shortcut as text so you don't need to define separate command for each tab

The documentation for all functions is available [here](http://copyq.readthedocs.io/en/latest/scripting-api.html).

```ini
[Command]
Command="
    copyq:
    shortcut = str(data(mimeShortcut))
    tabName = shortcut.slice(-1)
    tab(tabName)
    copy()
    write(
      0,
      mimeHtml, clipboard(mimeHtml),
      mimeText, clipboard(mimeText)
    )
    popup('Copied to tab ' + tabName)
    "
GlobalShortcut=alt+1, alt+2, alt+3
Icon=\xf064
Name=Copy To Tab
```

**Comment by User3985** [comment]
Thank you. Works wonderfully. Very quickly helps to organize information on different projects.
