### ISSUE TITLE
application/x-copyq-hidden doesn't work on 3.2

### ISSUE THREAD

**Issue by ipleten** [hluk/CopyQ#878]
Hidden item type stop working after 3.2 update.

**Comment by hluk** [comment]
Can you provide more info? Works fine for me: if an item has the format set to `1`, the content is hidden (if it's copied to clipboard, the content is not shown in window title).

**Comment by ipleten** [comment]
I have a separate "password" tab with encryption.
I used "hide/show item" macros (from docs) on notes to get only notes visible for these passwords.
Before 3.2 update all items  in tab were hidden and notes were visible.

I still can apply that macro to items and add "application/x-copyq-hidden" format but i need to use ctrl-arrow_left to get them hidden in tab.
After restart I see **both** notes and item content.
Here is how it looks after restart: 
![image](https://user-images.githubusercontent.com/6207156/36473701-05000a42-16fe-11e8-903a-86f448106c30.png)
but before 3.2 it was:
![image](https://user-images.githubusercontent.com/6207156/36473749-2b34ae20-16fe-11e8-9210-d7b8b853aa2a.png)

**Comment by hluk** [comment]
Sorry, I broke the behavior recently by requiring the "application/x-copyq-hidden" to be set to "1" (instead of being just empty). I should avoid doing such breaking changes in future.

**To fix this:** Remove the old command "Hide/Show Item Content" in Command dialog (F6), add [this one](https://github.com/hluk/copyq-commands/blob/master/Application/hide-item-content.ini) ([here is how to add the command to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)) and re-apply to all items again (CTRL+A to select all items in tab and select the command in toolbar, context menu or Item menu).

**Comment by ipleten** [comment]
It works like a charm now.
Thank you.
P.S: Was button "Commands/Global shortcuts" in "Shortcuts" menu tab removed intentionally? Seems F6 is the only one way to open it now.
P.P.S: I've just noticed that  "preview" window show hidden content:
![image](https://user-images.githubusercontent.com/6207156/36482794-0ea05880-171d-11e8-86ee-f7e3942a8d80.png)
but probably it expected behavior.

**Comment by hluk** [comment]
> Was button "Commands/Global shortcuts" in "Shortcuts" menu tab removed intentionally? Seems F6 is the only one way to open it now.

Yes, shortcuts (even global ones) for predefined and custom commands can be set directly in the Shortcuts configuration tab so you don't have to go to Command dialog for that and you can see all shortcuts in one place.

> I've just noticed that "preview" window show hidden content

Well that's something to consider for future releases. But create new issue if this is unexpected or not acceptable.
