### ISSUE TITLE
search for numbers with tray

### ISSUE THREAD

**Issue by araujorm** [hluk/CopyQ#882]
Hi.

I need to copy/paste that starts with numbers very often (like ip addresses) but that can't be searched on the tray since it will select some shortcuts beginning from 0 to 9 that I find useless.

I know someone asked exactly the opposite in:

https://github.com/hluk/CopyQ/issues/669

but is it possible to add an option to disable those shortcuts in the tray, since what I really care for is the tray search bar? Or does it exist and I am just missing it?

Thanks in advance.

**Comment by hluk** [comment]
I can add new option to search for number in tray menu and main window; it would disable selecting items by row.
![image](https://user-images.githubusercontent.com/38054/36800648-4e5a8b92-1cb0-11e8-8afc-053e9ad65d09.png)

**Comment by araujorm** [comment]
Seems perfect for me, that way it would please anyone according to their
preference.

**Comment by araujorm** [comment]
Hmm... wait, maybe you want to add that in the "Tray" tab? Because searching for numbers already works in main window.

**Comment by hluk** [comment]
Filtering numbers works in main window but it also prefers to jump to row number. E.g. searching for "192" would show all items containing "192" and row 192 which will be selected immediately even though previous items match -- and that can be annoying.

I've created single option for both tray and main window since the number filtering is very similar.
