### ISSUE TITLE
Script function open() no longer works with 3.2.0

### ISSUE THREAD

**Issue by reagle** [hluk/CopyQ#884]
My global shortcuts and actions (like looking something in an online dictionary) stopped working recently and I notice I got the 3.2 update about the same time. 

Perhaps the shortcut mechanism works, but the action doesn't. I can still cause copyq to popup with a global shortcut, but even when I select an action with my mouse it fails to do anything. I'm going to revert back a version and see if the functionality is restored.
<img width="868" alt="screen shot 2018-02-21 at 9 00 59 am" src="https://user-images.githubusercontent.com/596814/36484085-1f69232c-16e6-11e8-8c2a-4abbc67176b6.png">

**Comment by hluk** [comment]
Strange, indeed it doesn't work, even on Linux, but I don't see anything obvious that could break it.

Actually, the shortcut works fine but Qt fails to execute web browser. Maybe the problem is that now scripting doesn't run in GUI application.

Anyway, you can use following code instead:
```js
copyq:
query = encodeURI(str(clipboard()))
url = 'http://reagle.org/joseph/plan/search.cgi?sitesearch=MindMap&query=' + query
execute('open', url)
```

On Linux the last line would be:
```js
execute('xdg-open', url)
```

**Comment by hluk** [comment]
Fixed. (Opening web browser from non-GUI Qt application doesn't work.)

**Comment by reagle** [comment]
Thanks, once the next release appears in homebrew (usually pretty quick) I'll give it a go. Feel free to touch this issue to remind me (because I have the old CopyQ manually installed presently).
