### ISSUE TITLE
Systray icon out of place in Unity

### ISSUE THREAD

**Issue by wneuheisel** [hluk/CopyQ#914]
Last week, the CopyQ icon suddenly started appearing on the far left side of the Unity system tray. It actually covers the window close button now.

![screenshot from 2018-03-30 12 49 58](https://user-images.githubusercontent.com/4396872/38145954-d37e1dae-3419-11e8-8b81-1cded14bea10.png)

**Comment by hluk** [comment]
This looks like a really old issue. Isn't Unity desktop environment dead?

Anyway, I have no control over the icon placement. That's job for the Qt framework, other libraries in system and tray/notification area applet.

My suggestion is to disable the tray icon in configuration (the option is under Tray config tab).

**Comment by hluk** [comment]
Can you test this with CopyQ 3.3.1?

**Comment by jcoste-orange** [comment]
Hello,
I have the same problem as @wneuheisel.
The problem is still here with the new 3.3.1 version.

I run an old Ubuntu Trusty. Here is the version of the copyq dependencies :+1: 
libqt5svg5:amd64       5.2.1-1
libc6:amd64            2.19-0ubuntu6.14
libgcc1:amd64          1:4.9.3-0ubuntu4
libqt5core5a:amd64     5.2.1+dfsg-1ubuntu14.3
libqt5gui5:amd64       5.2.1+dfsg-1ubuntu14.3
libqt5network5:amd64   5.2.1+dfsg-1ubuntu14.3
libqt5script5:amd64    5.2.1+dfsg-1ubuntu1
libqt5widgets5:amd64   5.2.1+dfsg-1ubuntu14.3
libstdc++6:amd64       4.8.4-2ubuntu1~14.04.4
libx11-6:amd64         2:1.6.2-1ubuntu2
libxtst6:amd64         2:1.2.2-1

**Comment by wneuheisel** [comment]
It still persists for me in 3.3.1.

**Comment by hluk** [comment]
Closing. This is a very old issue, and I haven't encountered it for a long time.
