### ISSUE TITLE
Play sound on copy command script not working

### ISSUE THREAD

**Issue by technochitlin** [hluk/CopyQ#915]
Added the command script as it's shown on the website, but no sound will play. Attached is a pic of how I've got it set up- there's a red triangle next to the command so I suspect something is wrong...
![copyq](https://user-images.githubusercontent.com/737753/38156235-0f6e6a58-3442-11e8-9442-a7acf7139a34.jpg)

...and yes the sound file is in the Users folder and it will play :)

**Comment by technochitlin** [comment]
Note also If I activate it like this:
![copyq2](https://user-images.githubusercontent.com/737753/38165809-28008450-34df-11e8-8e46-24c0191111ce.jpg)
-the sound does not play and nothing is captured from the clipboard.

**Comment by hluk** [comment]
The copied command (starts with `[Command]`) needs to be pasted in the command list on left hand side. You can use "Paste Commands" button to do this (see [FAQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)).

Since this happens to others from time to time, I'll try to make it so that pasting command to the text box  also works.

**Comment by technochitlin** [comment]
Works like a charm, thanks!
