### ISSUE TITLE
Delete the first letter? 

### ISSUE THREAD

**Issue by itkind** [hluk/CopyQ#966]
Is it possible to configure CopyQ and to assign a hotkey for a special paste? So that the first letter of the copied text will be deleted? I work with Russian and Hebrew texts. 

Thank you.

**Comment by scottkosty** [comment]
I believe it should be possible. I suggest taking a read through the [Wiki](https://github.com/hluk/CopyQ/wiki). It takes some time, but it has a lot of useful information and you will want to do similar things in the future so you might as well put some time into it now. You might find the "Command examples" page on the Wiki useful.

Regarding Hebrew texts, I wonder if that will complicate things since the "first letter" would be the first letter from the right, correct?

Also I am curious, what is your use case?

**Comment by scottkosty** [comment]
@itkind I just wanted to make sure you saw my questions above.
