### ISSUE TITLE
Buttons in "Copyq action dialog" can't be pressed with keyboard

### ISSUE THREAD

**Issue by guraga** [hluk/CopyQ#981]
Steps to reproduce:
1. press hot key to open copyq window;
2. press F5 to show "copyq action dialog".

Actual behavior: buttons "apply", "save", "cancel" and "ok" does not have underlined character.

Expected behavior:  buttons must have underlined characters to allow press them using keyboard shortcuts.

**Comment by hluk** [comment]
This depends on platform (KDE, Windows, OS X have different behavior).

Pressing Alt can show the shortcuts (key hints).

**Comment by PhiLhoSoft** [comment]
It might be an issue with your translation.
I have a French interface (on Windows), and in this dialog, I only see the m shortcut on the Command field, after I hit Alt.

That's something I can fix on this translation, at least.
BTW, I tried to fix translations with the Weblate site, but it keeps banning me because my edit rate is too high, it is annoying... I guess I will fork this project and translate directly from the XML file.

**Comment by hluk** [comment]
> It might be an issue with your translation.

If that's the case, it's an issue in Qt since the buttons ("apply", "ok" ...) should be translated in Qt framework itself.

> I tried to fix translations with the Weblate site, but it keeps banning me because my edit rate is too high, it is annoying

Hmm, that's not good. Alternative is to fork this repo, use [Qt Linguist](http://doc.qt.io/qt-5/qtlinguist-index.html) and create PR.
